### ISSUE TITLE
[Bug]: When I copy part of the latex formula, the ob program crashes and gets stuck.

### ISSUE THREAD

**Issue by windily-cloud** [artisticat1/obsidian-latex-suite#10]
Reproduce：
1. Find a latex formula.
2. Mouse to select the part of the formula.
3. Press Ctrl + c
4. Get stuck

https://user-images.githubusercontent.com/30640638/163303518-05b97ddb-b48f-44d3-957a-affd217fc8f9.mp4

Other information:
1. When I turned off the wonderful plugin, everything was fine
2. win11 ，obisidan v0.14.5，latest plugin version

This is the best latex plugin I've ever used, I can't say enough.

Thank you for any reply!

**Comment by artisticat1** [comment]
Hello,

Glad you're enjoying the plugin! Unfortunately I'm unable to reproduce this bug. Does it still happen with all other plugins turned off? And only when copying math?

**Comment by windily-cloud** [comment]
I don't know what happened, but I can't reproduce this bug now either. I reported this problem in an obsidian group, and some people had the same problem as me, but now it's all gone.

This is a good thing, sorry to take up your valuable time to deal with this problem! I will definitely do a more general test next time, thank you very much for your reply. 

Good luck!

**Comment by artisticat1** [comment]
No problem! Glad it's solved :)
