### ISSUE TITLE
[Bug] $ inside math blocks triggers inline math preview

### ISSUE THREAD

**Issue by mzietlow** [artisticat1/obsidian-latex-suite#100]
## Describe the Bug

There are multiple ways of using $ inside math blocks. For example, one could write
``` markdown
$$
\text{this is legitimite: $\pi$}
$$
```

or

``` markdown
$$
1+1=\$
$$
```
Unfortunately, the dollar sign triggers the inline math preview when the cursor is placed _before_ the last additional dollar sign:

### Cursor placement before the first additional dollar sign (issue appears)
![Cursor placement before the first additional dollar sign](https://user-images.githubusercontent.com/30702083/208873302-ffb27b0f-f9f3-4e64-b9be-f8d4b0567c20.png)

### Cursor placement between the additional dollar signs (issue appears)
![Cursor placement between the additional dollar signs](https://user-images.githubusercontent.com/30702083/208873447-d96f686a-ba70-4264-9e75-25cfeffbc60e.png)

### Cursor placement after the additional dollar signs (issue does not appear)
![Cursor placement after the additional dollar signs](https://user-images.githubusercontent.com/30702083/208873534-a3ecb917-d7b5-47ac-8d11-0ff0d91ab0c7.png)

## How to Reproduce

1. Open a new vault and enable Latex Suite with inline math preview.
2. Create a new file and paste one of my samples.
3. Place the cursor before the last additional dollar sign
4. A preview pop-up will appear

## Expected Behavior

No preview pop-up should appear, since we are inside a math block, not inside an inline math statement

**Comment by artisticat1** [comment]
Fixed in 1.8.0.
