### ISSUE TITLE
-\infty conceals as -inf∞

### ISSUE THREAD

**Issue by cossio** [artisticat1/obsidian-latex-suite#101]
```
-\infty
```

is concealed as:

<img width="61" alt="Screenshot 2022-12-28 at 09 21 12" src="https://user-images.githubusercontent.com/10637482/209781492-712efc29-61c2-43f0-ac49-c423633087f6.png">

It should conceal the `inf` prefix too.

**Comment by artisticat1** [comment]
Thanks for reporting this. It'll be fixed in the next release.
