### ISSUE TITLE
Clicking on an equation block places the cursor somewhere else (instead of editing the equation block)

### ISSUE THREAD

**Issue by cossio** [artisticat1/obsidian-latex-suite#103]
This happens to me frequently. I'm not sure if it's related to the conceal feature, which confuses Obsidian about where it should place the cursor.

Has anyone else noticed this?

Unfortunately it's not something I can reproduce consistently yet. Actually I'm not even sure it's related to this plugin, but since I always have this plugin activated (and it's the only plugin I have), and the issue happens only with equations, I thought it was worthwhile to ask, in case someone else sees the same.

Also in case someone has ideas to help debug / pinpoint the situation that triggers this.

**Comment by artisticat1** [comment]
I have also experienced this and am pretty sure it's a bug in Obsidian, not this plugin.

I'm going to close this issue, but feel free to reopen it if you think the problem lies with this plugin (and perhaps file a bug report on the Obsidian forums).

**Comment by artisticat1** [comment]
> Did you happen to find conditions under which this is triggered consistently?

No, unfortunately not!
