### ISSUE TITLE
\color can be typed in math $$

### ISSUE THREAD

**Issue by Sheldontao** [artisticat1/obsidian-latex-suite#106]
because `lor` is treated as `\lor`, so I can't type `\color `to colorize my latex
<img width="177" alt="image" src="https://user-images.githubusercontent.com/36765652/210970325-cf1619ab-3006-4504-b736-bda8c72ca0e9.png">

**Comment by Sheldontao** [comment]
and the the config has no such word

**Comment by artisticat1** [comment]
You could use the snippet

```typescript
{trigger: "col", replacement: "\\color", options: "mA"},
```

Does this solve your issue?

**Comment by Sheldontao** [comment]
what's the difference between \\color and \color?

**Comment by Sheldontao** [comment]
> You could use the snippet
> 
> ```ts
> {trigger: "col", replacement: "\\color", options: "mA"},
> ```
> 
> Does this solve your issue?

what's the difference between \color and \color?

**Comment by Sheldontao** [comment]
thanks so much!!!!

**Comment by Sheldontao** [comment]
> You could use the snippet
> 
> ```ts
> {trigger: "col", replacement: "\\color", options: "mA"},
> ```
> 
> Does this solve your issue?

thanks so much!!!!
