### ISSUE TITLE
Tab behaviour with fractions in align environment (including auto-fractions)

### ISSUE THREAD

**Issue by celdorwow** [artisticat1/obsidian-latex-suite#112]
First of all, thanks for the addon. It's such a Quality of Life improvement, especially when it comes to writing LaTeX.

Secondly, I am currently working on `Obsidian v1.1.9` and `Latex Suite 1.6.11`.

---

Here is the issue.

For clearer code, I always insert indention before each line inside `align`. I find TAB does not work as expected with fractions. I tested both `Auto-fraction` and a rule  for a manual replacement for fractions and it seems the issue is exactly the same.

Consider following expression inside `align`:
```latex
$$
\begin{align}
    s = t \\<curseor>
\end{align}
$$
```
at this stage when I hit ENTER, I get to new line with indentation as expected:

```latex
$$
\begin{align}
    s = t \\
    <cursor>
\end{align}
$$
```

Then, if I write `a/`, it triggers `Auto-fraction` but the fraction is not indented but its numerator receives TAB: 

```latex
$$
\begin{align}
    s = t \\
\frac{    a}{}
\end{align}
$$
```

I thought I would solve the problem if I create a manual rule for fractions and disable `Auto-fraction`

     {trigger: "(.*)/", replacement: "\\frac{[[0]]}{$0}$1", options: "rmA"},

but it seems the outcome is exactly as if I kept using `Auto-fraction`.

At this point I guess if there's a bug, it is related to `\frac{...}{...}` itself, rather than `Auto-fraction`.

Thanks

**Comment by artisticat1** [comment]
In the plugin settings, add a literal tab character "	" to the "breaking characters" setting under auto-fraction, and this will resolve your problem.

I'll include it by default in future releases.
