### ISSUE TITLE
Turning natural language into LaTex with ChatGPT

### ISSUE THREAD

**Issue by louis030195** [artisticat1/obsidian-latex-suite#113]
Hey, love your plugin 🚀

If you want to expand your LaTex workflow further, you can try https://github.com/louis030195/obsidian-ava to generate LaText from natural language in a second:

https://user-images.githubusercontent.com/25003283/214030314-d77bd219-b72f-4758-b9e0-c8eb7af6ed1e.mov

**Comment by artisticat1** [comment]
Cool, thanks for sharing!
