### ISSUE TITLE
Fix conceal of \middle

### ISSUE THREAD

**Issue by cossio** [artisticat1/obsidian-latex-suite#114]
Currently,
```
$$P\left( \sum_{i} x_{i} = 1 \middle| z = 0 \right)$$
```
conceals as:

![Screenshot 2023-01-28 at 22 03 04](https://user-images.githubusercontent.com/10637482/215290973-3b77e4bb-306b-4c4d-8729-4d17b719e90f.png)

So it conceals only the `\mid` part of `\middle`, and shows this weird dangling `/dle`.

The `\middle` (inside a `\left,\right` pair as in this example), should make the bar `|` stretch to the same size of the surrounding parenthesis. This is how it looks rendered (in Obsidian, so MathJax supports this alright):

![Screenshot 2023-01-28 at 22 04 26](https://user-images.githubusercontent.com/10637482/215291021-0942c107-8c30-451f-b785-97bd0c2a9f40.png)

**Comment by artisticat1** [comment]
Thanks for reporting! Fixed in 1.6.12.
