### ISSUE TITLE
[Feature request] Add `c` as snippet mode

### ISSUE THREAD

**Issue by MultisampledNight** [artisticat1/obsidian-latex-suite#115]
I'm using this awesome plugin together with your [TikZJax](https://github.com/artisticat1/obsidian-tikzjax) plugin, and it's a blast so far! There's only the minor nit that often I'd like to type snippets that

- should _only_ run in codeblocks (for example, a `\begin{$0}$1\end{$0}` helper that should auto-expand)
- should _never_ run in codeblocks (for example, `->` expanding to `\longrightarrow` in text mode)

I don't know TypeScript, but I'd love to implement this, if that'd be advisable and acceptable! From looking a bit around in the source code, I think `withinMath` would need to be changed to an enum containing all possible modes:

https://github.com/artisticat1/obsidian-latex-suite/blob/efb2936982c926db68a7790bfeccac55815f3b37/src/main.ts#L323-L324

Alongside of some pattern matching instead of these lines:

https://github.com/artisticat1/obsidian-latex-suite/blob/efb2936982c926db68a7790bfeccac55815f3b37/src/main.ts#L488-L493

Additionally, I'm not sure if it would be worth supporting math mode stacked ontop of codeblock mode _inside_ of a codeblock, in the case of typing `tikz`/`latex` codeblocks? I often find myself typing `$\alpha$` in labels or the like where `mk@a` would have been more comfortable. How should the mode look like as data structure, then?

**Comment by MultisampledNight** [comment]
Actually, from thinking about this, it might be worth turning the entire structure of snippets into a bitfield, in the sense of

```ts
class Mode {
    text: boolean;
    math: boolean;
    code: boolean;
}
```

This way a snippet with the options `tmcW` would be runnable inside of _all_ three modes, as opposed to the current implementation, which only allows snippets to be run in _either_ `m` _or_ `t`, even if both are specified in the options!

**Comment by artisticat1** [comment]
> I don't know TypeScript, but I'd love to implement this, if that'd be advisable and acceptable!

That'd be great! You're more than welcome to implement this. Let me know if you'd like any pointers or help finding your way around the code.

> Actually, from thinking about this, it might be worth turning the entire structure of snippets into a bitfield, in the sense of
> 
> ```ts
> class Mode {
>     text: boolean;
>     math: boolean;
>     code: boolean;
> }
> ```

Yes, I've been meaning to do some refactoring and introduce a structure like this!

We should additionally include fields to distinguish between inline and block math, and also whether the cursor is currently inside a `\text{}` environment within math. (This will help solve #56 and #100.)

> This way a snippet with the options `tmcW` would be runnable inside of _all_ three modes, as opposed to the current implementation, which only allows snippets to be run in _either_ `m` _or_ `t`, even if both are specified in the options!

By the way, you can already allow a snippet to run in any mode by omitting the options `m` and `t` entirely.

**Comment by MultisampledNight** [comment]
Alright, thank you! Very possible that work on this might be slow/delayed, I've got quite a lot going on IRL at the moment.

About the modes, I think to preserve backwards compatibility and for semantic purpose it might be useful to have no mode set for the snippet to be equal to _all_ modes.

And another sidenote for myself, for `php`, `perl`, `julia`, `sh` and `bash` codeblocks, we definitely do not want math mode to be active even with `$`.

**Comment by eiiot** [comment]
Was there ever any progress made in implementing TikZ snippets / support? If not, I'd love to contribute some snippets...
