### ISSUE TITLE
The default behaviour of dm causes obsidian bugs

### ISSUE THREAD

**Issue by lukks22** [artisticat1/obsidian-latex-suite#117]
It's more of an Obsidian bug but easily avoidable so I'm putting here. As you can see [here](https://forum.obsidian.md/t/discrepancy-between-handling-of-math-blocks-in-live-preview-and-reading-view/44319), if I were to write:
`something dm my math equation`

The snippet would transform it in
``something $$

my math equation

$$``

Which can cause problems as you can see in the forum. It's easily avoidable adding "\n" both at the start and the end of the snippet for dm. The char at the end is because the same problem can occur if there's a text right after the closing math block tag. The real problem is that this problem doesn't reveal in live preview mode but just in the reading mode, which can be annoying as you'd only realise it after you've written all of your equations

**Comment by artisticat1** [comment]
As you say, this is more of an issue with Obsidian and not this plugin, which only aims to make typing LaTeX easier. 

It's easily resolvable by inserting line breaks before typing an equation. Users can also modify the `dm` snippet if they wish, so I'll leave the `dm` snippet as it is for now, and close this issue.
