### ISSUE TITLE
Some currencies break render

### ISSUE THREAD

**Issue by martinmenge** [artisticat1/obsidian-latex-suite#119]
When using Euro symbol the Latex does not render.

$$R=€  = \frac{\$ \ value \ of \ £}{$ \ value \ of \ €} = \frac{2}{1.25} = 1.60$$

I tried to escape it as such:
$$R= \€  = \frac{\$ \ value \ of \ £}{$ \ value \ of \€ } = \frac{2}{1.25} = 1.60$$

However that renders the connected slash as well. If the slash does not touch, it does not render.
But this works: 
$$R= Euro  = \frac{\$ \ value \ of \ £}{$ \ value \ of \ euro } = \frac{2}{1.25} = 1.60$$

**Comment by artisticat1** [comment]
This is an issue with Obsidian / MathJax, and not this plugin. Try raising an issue on one of their forums.
