### ISSUE TITLE
Mobile compatibility

### ISSUE THREAD

**Issue by kometenstaub** [artisticat1/obsidian-latex-suite#12]
Is there a reason why `isDesktopOnly` is set to `true`?
I looked at the imports and didn't see a reason why it shouldn't work on mobile.

**Comment by artisticat1** [comment]
Yes, I tested the plugin on mobile, and found that it seemed to work except that it failed to detect when the cursor was inside math. (So snippets set to run outside math (such as "dm") worked, but none of the math-related functions worked.)

I'll do some debugging and try to get it working.

**Comment by artisticat1** [comment]
Added in 1.1.0.
