### ISSUE TITLE
Snippet with `\bigcup` only triggers in display mode.

### ISSUE THREAD

**Issue by jmmaloney4** [artisticat1/obsidian-latex-suite#121]
I have the following snippet:
```
{trigger: "\\U", replacement: "\\bigcup_{ ${0:j}=${1:1} }^{${3:\\infty}} $2", options: "mA"},
```
but I can only get it to trigger in display mode math, and not inline math. Is this expected behavior? Is there someway to override this behavior to make it work in inline math?

Thank you for an excellent plugin.

**Comment by zcysxy** [comment]
You can add an space: `"\\U "`

**Comment by artisticat1** [comment]
See #223 for an explanation of why this happens.
