### ISSUE TITLE
Display `\limits`

### ISSUE THREAD

**Issue by YIRU69** [artisticat1/obsidian-latex-suite#125]
Hi, the new vision `limits` have not hide.
![image](https://user-images.githubusercontent.com/48148292/222908501-50d36b6b-01d0-45be-a609-98acd175cfa5.png)

**Comment by artisticat1** [comment]
Can you share the LaTeX source for this equation?

**Comment by YIRU69** [comment]
HI, 
```
$\lim\limits_{ n \to \infty }[(a_{n}-b_{n})+a_{n}+b_{n}]=\lim\limits_{ b \to \infty }2a_{n}$
```

**Comment by YIRU69** [comment]
@artisticat1 Excuse me, do you happen to be following this issue?
