### ISSUE TITLE
[BUG] Chinese parenthesis can't auto replace.

### ISSUE THREAD

**Issue by jerviscui** [artisticat1/obsidian-latex-suite#129]
I create a rule to replace the Chinese parenthesis in the code line.

```
{trigger: "`(.*)（）", replacement: "`[[0]]()", options: "rt"},
```

The options are "rt", and it works when I press the Tab.
But if I set options to "rtA", it doesn't work.

The test code: `abc（）`

**Comment by zcysxy** [comment]
Works for me

**Comment by jerviscui** [comment]
> Works for me

I'm now using a global way of handling Chinese and English symbols, like AHK. 
So I didn't try this again.

**Comment by zcysxy** [comment]
👍 Then I think this issue is stale. Maybe you can close it for the convenience of maintenance.
