### ISSUE TITLE
Enabling "Tabout" prevents list indentation using tab

### ISSUE THREAD

**Issue by lumitry** [artisticat1/obsidian-latex-suite#13]
When "Tabout" is enabled and you use the tab key (when in a list and not in inline LaTeX), the default behavior in Obsidian is to further indent items in a list. When using this plugin with tabout enabled, pressing tab instead takes you to the start of the next item in the list.

Note that this includes checklists, so when pressing tab at the end of an item in a checklist will go to just after the close brackets of the next item:
` - [ ]`
____^ here, without a space afterwards, thus breaking the checklist if you were to write there

When reaching the end of a list, the plugin will navigate to the start of the next list in the file. When there is no more LaTeX and no more lines in the file, tabbing still works as expected.

**Comment by artisticat1** [comment]
Thanks for reporting, I've fixed this in 1.1.1.
