### ISSUE TITLE
[Feature Request] Preview Block Math in Source Mode

### ISSUE THREAD

**Issue by IntrovertHedgehog** [artisticat1/obsidian-latex-suite#130]
I really like the inline math preview function, and it works even in source mode. However, there's no math preview for block math in source mode (since it's default in preview mode I think). It would be nice to have a preview similar to that of inline math.

**Comment by StrangeGirlMurph** [comment]
I am considering creating this. 

@artisticat1 was there a reason you didn't do it? 
I don't want to waste my time in case there is something weird/hard about this ^^
