### ISSUE TITLE
vim mode can sometimes trigger snippet

### ISSUE THREAD

**Issue by npadmana** [artisticat1/obsidian-latex-suite#15]
First, thank you very much for developing this -- this really does make working with LaTeX in Obsidian much nicer.

I wanted to report an issue that I'm having with snippets in vim-mode. Because moving up a line uses `k`, if you move up a line where the character before is a `k`, this triggers the snippet.

As an example, suppose I am in command mode and my cursor is on the `a` below.
```
math is fun
 ^
```
If I move up a line with `k`, this goes to 
```
$$ath is fun
```
Unfortunately, I'm relatively new to obsidian, so not sure how the plugins work, but this might be as simple as disabling snippets when in command mode when using vim key bindings.

Again, thanks for a very useful plugin.

**Comment by artisticat1** [comment]
Glad you find the plugin useful!

I'll try to fix this soon by only executing snippets while in insert mode.

**Comment by artisticat1** [comment]
Thanks for reporting the issue. It should now be fixed in 1.1.2.
