### ISSUE TITLE
[BUG] manually enlarged brackets should not change when auto-enlarge brackets is triggered

### ISSUE THREAD

**Issue by AminGholizad** [artisticat1/obsidian-latex-suite#156]
# Description
When auto-enlarge brackets is enabled It should not enlarge the brackets that are manually enlarged like `\biggl(` and `\biggr)`.
the reason I use `\biggr)` is that `\left(` does not work when you have sum that is broken up in multiple lines with ` \\ ` (latex gives an error that the matching `\right)` is not there).

# To Reproduce
Just have a sum that is broken up to multiple lines and use  `\biggl(` and`\biggr)` to enclose those lines to indicate that they are inner part of the sum.  Then `\biggl(`, `\biggr)` will become  `\biggl\left(`and `\biggr\right)` when triggered.

# Expected Behavior
leave out manually enlarged brackets like `\biggl(`, `\biggr)` as is.

**Comment by artisticat1** [comment]
Closing in favour of #268
