### ISSUE TITLE
[feature request]: Support for function extension snippets

### ISSUE THREAD

**Issue by windily-cloud** [artisticat1/obsidian-latex-suite#16]
This plugin works well enough and very elegantly allows me to edit latex formulas.

If it could support function fragments, it would be perfect! My thoughts are as follows.

`mxi(3)` outputs a `3x3` unit matrix and `mxi(6)` outputs a `6x6` unit matrix.I can also customize `h(3)` to output three-level headings.

Also, it would be easier to debug and backup if the configuration file could be separated into an md file.

Thanks for any replies, I really love this plugin!

**Comment by artisticat1** [comment]
> `mxi(3)` outputs a `3x3` unit matrix and `mxi(6)` outputs a `6x6` unit matrix.I can also customize `h(3)` to output three-level headings.

I'll need to put some thought into how to achieve this. I guess the goal is to allow executing code within a snippet, right?

> Also, it would be easier to debug and backup if the configuration file could be separated into an md file.

Good idea! I could add a button to export the user's snippets to a .txt or .md file, and a button to load snippets from a .txt / .md file. Would that work for you?

Your plugin settings (including snippets) should be backed up by git / any sync service you're using, btw.

> Thanks for any replies, I really love this plugin!

Glad you enjoy it!

**Comment by windily-cloud** [comment]
> I'll need to put some thought into how to achieve this. I guess the goal is to allow executing code within a snippet, right?
I'm not quite sure there's a better way to implement this feature. My idea is to type the function name and parameters, then output the snippet returned by the function.

I've seen people implement it like this(I forget exactly where it came from, I retrieved it from last year's photo gallery😂):

![{9CF982E7-D6C5-FCEF-058A-18C449468135}](https://user-images.githubusercontent.com/30640638/168410211-c85df094-cad7-4bae-a894-40a642dfa255.jpg)

I guess his idea  is to use regular expressions to extract the function name and parameters, and then output the snippets returned by the function if it matches the preconfigured function.This avoids the case of entering more parentheses, and I don't know if there are any side effects.

![image](https://user-images.githubusercontent.com/30640638/168410570-8f3e03ef-2175-47c0-a3e6-da15fdfd24e9.png)

Of course, this is just an idea, we can have a more elegant approach. This method of his has to manually modify the code optimization himself when dealing with multiple parameters or when the parameters are arrays.

Anyway, I'm convinced you can handle this gracefully because you made this plugin to make me feel graceful, haha😆！If I can be of any help, just ask, I'm happy to do so. For example, manually testing the functionality and stability of new features.

Thanks again!

**Comment by artisticat1** [comment]
> Anyway, I'm convinced you can handle this gracefully because you made this plugin to make me feel graceful, haha😆！If I can be of any help, just ask, I'm happy to do so. For example, manually testing the functionality and stability of new features.

Haha, thank you! I'd be happy to have help with testing. I'll let you know when I have things ready.

So, I've come up with an idea for how to achieve this. To achieve your example with "a33pmx" above, here's what it would look like.

We can use the regular expression

`([A-Za-z])([0-9])([0-9])pmx`

to match the string "a33pmx". This regex captures the groups "a", "3", and "3". I assume these are the symbol of the matrix, the number of rows, and the number of columns.

Then we can write a function in javascript that takes the inputs "a", "3", and "3" as parameters and generates the corresponding matrix output in LaTeX. The plugin will pass in the capture groups to the function as an array.

```javascript
function genMatrix(captureGroups) {
  const [symbol, rows, columns] = captureGroups;

  let arr = [];
  for(let j = 0; j < rows; j++) {
      arr[j] = [];

      for(let i = 0; i < columns; i++) {
          arr[j][i] = `${symbol}_{${j+1}${i+1}}`;
      }
  }

  let output = arr.map(el => el.join(" & ")).join(" \\\\\n");
  output = `\\begin{pmatrix}\n${output}\n\\end{pmatrix}`;

  return output;
}
```

![image](https://user-images.githubusercontent.com/100622574/168422128-45f96c42-d44d-49c8-be2a-9d157e988211.png)

Finally, we put all this together in a snippet that we can run by typing "a33pmx<kbd>Tab</kbd>".

```typescript
{trigger: "([A-Za-z])([0-9])([0-9])pmx", replacement: `

function genMatrix(captureGroups) {
  const [symbol, rows, columns] = captureGroups;

  let arr = [];
  for(let j = 0; j < rows; j++) {
      arr[j] = [];

      for(let i = 0; i < columns; i++) {
          arr[j][i] = \`\${symbol}_{\${j+1}\${i+1}}\`;
      }
  }

  let output = arr.map(el => el.join(" & ")).join(" \\\\\n");
  output = \`\\begin{pmatrix}\n\${output}\n\\end{pmatrix}\`;

  return output;
}

`, options: "rmx"}
```

Similarly, we can create a snippet for unit matrices, as you suggested in your first post.

![image](https://user-images.githubusercontent.com/100622574/168422782-fb70695d-be0b-43a1-9ab1-f276cfc4ce52.png)

```typescript
{trigger: "mxi([0-9])", replacement: `

function genMatrix(captureGroups) {
  const [N] = captureGroups;

  let arr = [];
  for(let j = 0; j < N; j++) {
      arr[j] = [];

      for(let i = 0; i < N; i++) {
          arr[j][i] = (i === j) ? 1 : 0;
      }
  }

  let output = arr.map(el => el.join(" & ")).join(" \\\\\n");
  output = \`\\begin{pmatrix}\n\${output}\n\\end{pmatrix}\`;

  return output;
}

`, options: "rmx"}
```

Here typing "mxi6<kbd>Tab</kbd>" will create a 6x6 unit matrix.

How does this sound?

**Comment by windily-cloud** [comment]
Wow, that's great, I was confused about function names and passing parameters, and you've solved it elegantly. This allows me to customize the trigger keyword without worrying about the function name on the one hand, and to pass precise parameters on the other.

Excited, excited, or excited！I can't wait to try this feature, provided you don't work too hard.

**Comment by artisticat1** [comment]
Great! ❤️ I am currently busy, so I'm not sure exactly when I can start working on it, but hopefully within the next few weeks or so.

**Comment by TimothyBesada** [comment]
I just wanted to check if you're still thinking of implementing this? I think your idea of being able to run some code in the replacement options is a really good way of doing this.

**Comment by artisticat1** [comment]
It's in the backlog at the moment, but any PRs to implement this would be welcome.

**Comment by vincentssn** [comment]
Hi.
I just wanted to make sure that are there any release supporting this feature？
It would be a great improvement for typing matrix in Linear Algebra.
Best regard!

**Comment by vincentssn** [comment]
> Hi. I just wanted to make sure that are there any release supporting this feature？ It would be a great improvement for typing matrix in Linear Algebra. Best regard!

In ultisnips of vim, it implements this feature by supporting running function or script. just like:

define func:
def add_row(snip):
	row_len = int(''.join(s for s in snip.buffer[snip.line] if s.isdigit()))
	old_spacing = snip.buffer[snip.line][:snip.buffer[snip.line].rfind('\t') + 1]
	snip.buffer[snip.line] = ''
	final_str = old_spacing
	final_str += " & ".join(['$' + str(j + 1) for j in range(row_len)])
	final_str += " \\\\\\"
	snip.expand_anon(final_str)
endglobal

then:
pre_expand "add_row(snip)"
snippet "tr(\d+)" "Add table row of dimension ..." r
endsnippet

so I can type tr(4) [tab] to enlarge one row of 4 numbers in latex text like
 [cursor] & [cursor] & [cursor] & [cursor] \\
Type tab can jump cursor to the next position.

**Comment by yfzhao20** [comment]
Looking foward to this function! 

Previously I found a similar extension in VS Code: [`draivin.hsnips`](https://github.com/draivin/hsnips#snippets-file). `global` function was implemented in this extension and may provide some inspiration.  

```js
global
// JavaScript code
endglobal
```

**Comment by artisticat1** [comment]
> If I understand correctly, the `x` option would indicate a function being evaluated. So what would need to be done in a PR would be identifying if the `x` option is present, and if so running the javascript function and returning the output? Am I correct in thinking that except for adding the `x` option as a possibility to settings etc., all the changes would occur in `run_snippet.ts`? Sorry, I'm not very familiar making PRs but happy to give it a go!

Yes, exactly. However, I now realise a cleaner solution than adding an `x` option may be to simply allow the `replacement` of a snippet to be a string or a function. Then snippets could look something like

```typescript
{trigger: "mxi([0-9])", replacement: (result: RegExpMatchArray) => {
  const N = result[1];

  const arr = [];
  for(let j = 0; j < N; j++) {
      arr[j] = [];

      for(let i = 0; i < N; i++) {
          arr[j][i] = (i === j) ? 1 : 0;
      }
  }

  const output = arr.map(el => el.join(" & ")).join(" \\\\\n");
  return `\\begin{pmatrix}\n\${output}\n\\end{pmatrix}`;

}, options: "rm"}
```

So you'd need to modify the definition of a `Snippet` to give the `replacement` the type `string | ((result: RegExpMatchArray) => string)`, and modify `run_snippets.ts` as you mention.

However, snippets are currently parsed using json5, which does not allow parsing functions - so we would probably need to switch to using a javascript parser for parsing snippets as well.

Feel free to have a go if you are still interested!

**Comment by artisticat1** [comment]
Added in 1.9.0 [(see the docs here)](https://github.com/artisticat1/obsidian-latex-suite/blob/main/DOCS.md#function-snippets).
