### ISSUE TITLE
Make default background colour for the mathjax preview tooltip NOT the same as the editor background

### ISSUE THREAD

**Issue by universemaster** [artisticat1/obsidian-latex-suite#164]
https://github.com/artisticat1/obsidian-latex-suite/blob/1fbcf544db94221075268ed48359da84573ab071/src/editor_extensions/math_tooltip.ts#L66C20-L66C47

Currently the default background colour for the mathjax preview tooltip is the same as the editor background, which causes confusion (especially when it appear on top of other math).

Personally, I am using the following snippet to change to a grey color, but I think the default should be changed too to something other than matching the background.

```
.cm-tooltip.cm-tooltip-cursor {
    background-color: rgb(113, 113, 113) !important;
}
```

**Comment by artisticat1** [comment]
Implemented in 1.8.0.
