### ISSUE TITLE
[BUG] cannot disable the rendering of ll (double lowercase L)

### ISSUE THREAD

**Issue by blackdecker43** [artisticat1/obsidian-latex-suite#175]
# Description
I cannot disable the rendering of ll (double lowercase L). It always translates to <<. I searched over the snippet in the plugin setting, delete all of them, searched though the main.js file, also delete all of them. However, when I type ll, it is still regonized.

I want to disable it because I prefer to have a snippet for \forall. It is overwritten by the rendering of ll.

I am using macOS Monterey 12.6. Obsidian Version 1.3.7.

Thanks in advance for your help.

**Comment by Flecart** [comment]
Getting this error too, i can't write `\forall` for example

**Comment by Fusaaaann** [comment]
Getting this error too, but things seems "resolved" by adding this line to the snippet:
```
    {trigger: "\\foral", replacement: "\\forall", options:"mA"},
```
Hopefully "\\foral" does not conflict with other command.

**Comment by Obskyur** [comment]
Hey guys! I found the problem / solution:
#### Problem:
From [Latex Suite Documentation](https://github.com/artisticat1/obsidian-latex-suite/blob/main/DOCS.md) (around the bottom of the page), we get:
```js
"${SYMBOL}" = "hbar|ell|nabla|infty|dots|leftrightarrow|mapsto|setminus|mid|cap|cup|land|lor|subseteq|subset|implies|impliedby|iff|exists|equiv|square|neq|geq|leq|gg|ll|sim|simeq|approx|propto|cdot|oplus|otimes|times|star|perp|det|exp|ln|log|partial"
```

This means any time `${SYMBOL}` is used in the snippets, it is looking for any of the above strings.

#### Solution:
1. Navigate to `...\Obsidian Vault\.obsidian\plugins\obsidian-latex-suite`
2. Open `main.js` in a code / text editor
3. Search for "SYMBOL"
4. Remove "|ll" from the series of OR statements in the variable assignment

Hope this helps!

**Comment by artisticat1** [comment]
In the latest release, you can now edit `${SYMBOL}` in the plugin settings as Obskyur described.
