### ISSUE TITLE
FR: Paired symbol matching

### ISSUE THREAD

**Issue by YIRU69** [artisticat1/obsidian-latex-suite#18]
I love your plugin, use it everyday.
So I have some suggestions about paired symbol like (),{},[]
such as the picture, Can you make it appear in the obsidian notes?
![image](https://user-images.githubusercontent.com/48148292/169648394-c238e817-977c-4085-8c99-d4fe4c0fef0a.png)

**Comment by YIRU69** [comment]
Many time I want to chech my latex format. It is so difficult to find what paired symbol I loss.

**Comment by artisticat1** [comment]
I agree, highlighting paired symbols would be a nice feature to have!

It should be easy to implement since CodeMirror has an extension for this. I'll try to get around to this within the next few weeks.

**Comment by YIRU69** [comment]
Thank you very muchhhhhhhhhhhhhhhhhh!

**Comment by artisticat1** [comment]
I've been working on this. As a bonus, all matching brackets are highlighted in the same color (like in Bracket Pair Colorizer), not just the brackets beneath the cursor:

https://user-images.githubusercontent.com/100622574/173138449-b080944e-4722-420d-a8ea-a9ba38602000.mp4

Just working on styling and bug fixes before it's released.

**Comment by YIRU69** [comment]
Thank you @artisticat1 , it is a good news on the morning.

**Comment by artisticat1** [comment]
Sorry for the delay! This is ready to be released. I'm just waiting for Obsidian v0.15 to be made available to the public before I release it :)

**Comment by YIRU69** [comment]
> Sorry for the delay! This is ready to be released. I'm just waiting for Obsidian v0.15 to be made available to the public before I release it :)

OK, get it!
