### ISSUE TITLE
[BUG] Default snippets don't include secant

### ISSUE THREAD

**Issue by BionicBison05** [artisticat1/obsidian-latex-suite#183]
# Description

The default snippets include shortcuts for every trig function besides secant
# To Reproduce

Type another trig function, `sin` for example, and observe that it is expanded correctly. Now type `sec`.
# Expected Behavior

`sec` is expanded into `\sec` and a space is inserted after upon typing more characters

**Comment by Comprehensive-Jason** [comment]
This is a super easy fix. Done in #195
