### ISSUE TITLE
[BUG] Latex suite causes the canvas cards to be misty on source view mode.

### ISSUE THREAD

**Issue by CamWam** [artisticat1/obsidian-latex-suite#187]
# Description
It seems that Latex Suite will cause the canvas card’s content to be misty on source view mode.
In past versions, it only happened in selecting condition, but now it has become worse
I have tried to restart the software, open safe-mode and close it, and close all other plugins.

# To Reproduce

https://github.com/artisticat1/obsidian-latex-suite/assets/73453314/54d97c77-5aa3-49b0-ae2b-533a88a70e86

https://github.com/artisticat1/obsidian-latex-suite/assets/73453314/7a4374e5-3f56-4a53-944e-b89f15773707

typing in canvas's card, it will reappear

Window 10
Obsidian v1.4.12

**Comment by Comprehensive-Jason** [comment]
I'm having this same issue. It's quite weird.

https://github.com/artisticat1/obsidian-latex-suite/assets/68677082/375dca78-82b1-4397-99e2-add713e8f738

**Comment by artisticat1** [comment]
I can't reproduce this. Does the issue occur if you disable all features in the plugin settings?

**Comment by CamWam** [comment]
> I can't reproduce this. Does the issue occur if you disable all features in the plugin settings?

Well, it seems doesn't happen in MacOS, only happens on WindowsOS. I have tried to disable all features in the plugin settings. but it doesn't change anything.

**Comment by j-finger** [comment]
I have been encountering a peculiar blurring issue with the Latex Suite plugin on Obsidian, specifically affecting the canvas cards. The blurring manifests whenever a card contains either a Latex equation or a list with more than two items. I have documented this issue through several screenshots.

Here are the detailed observations and circumstances under which the blurring occurs:

1. **Latex Equations and List Items:**
   - The blurring is triggered when a card has a Latex equation or a list with more than two items.
   - Notably, if the first item of a list is selected and being edited, the blurring does not occur. However, from the second item onwards, the blurring is present.

2. **Editing and Viewing Modes:**
   - The blurring is present in both editing mode (under the aforementioned circumstances) and viewing mode (if the card contains a Latex equation or a list).

3. **Settings and Restart Attempts:**
   - I tried to resolve the issue by toggling various settings on and off, including disabling and re-enabling the extension, coupled with restarting Obsidian. Unfortunately, these actions did not ameliorate the blurring issue.

I have captured screenshots illustrating the blurring issue, which can be provided for further analysis.

![all LatexSuite settings disabled   still blurry](https://github.com/artisticat1/obsidian-latex-suite/assets/80647966/a96252d6-c31d-4a69-95de-35140cca7f6f)
all LatexSuite settings disabled   still blurry

![blurry editing equation](https://github.com/artisticat1/obsidian-latex-suite/assets/80647966/de77ae07-0fef-4fce-b608-bc7e12e60fb4)
blurry editing equation

![blurry editing list](https://github.com/artisticat1/obsidian-latex-suite/assets/80647966/e3c84b40-2c7c-4b7f-888e-2bc16da9da8b)
blurry editing list

![clear - extension disabled](https://github.com/artisticat1/obsidian-latex-suite/assets/80647966/b05298cd-cd39-4514-b41c-07f04a0bae14)
clear - extension disabled

![Unselected Card and blurry](https://github.com/artisticat1/obsidian-latex-suite/assets/80647966/7a1bd5ff-463e-4fff-b11c-b0d6dfca4af3)
Unselected Card and blurry

**Comment by CamWam** [comment]
I find a way to solve this problem.
1. Open ".obsidian\plugins\obsidian-latex-suite"
2. find "styles.css"
3.  comment out `.snippets-editor-wrapper .cm-editor, .cm-scroller {
    border-radius: 4px;
}
`  to `/* .snippets-editor-wrapper .cm-editor, .cm-scroller {
    border-radius: 4px;
} */`

It works in 
obsidian v1.3.7 , Latex suite 1.74/1.8.8

**Comment by j-finger** [comment]
> 1. Open ".obsidian\plugins\obsidian-latex-suite"
> 2. find "styles.css"
> 3. comment out `.snippets-editor-wrapper .cm-editor, .cm-scroller { border-radius: 4px; } `  to `/* .snippets-editor-wrapper .cm-editor, .cm-scroller { border-radius: 4px; } */`


Can confirm this works! Happy days!

![image](https://github.com/artisticat1/obsidian-latex-suite/assets/80647966/f9af43e2-4ee3-405e-8fe5-61e6cface711)

**Comment by artisticat1** [comment]
> I find a way to solve this problem.
> 
> 1. Open ".obsidian\plugins\obsidian-latex-suite"
> 2. find "styles.css"
> 3. comment out `.snippets-editor-wrapper .cm-editor, .cm-scroller { border-radius: 4px; } `  to `/* .snippets-editor-wrapper .cm-editor, .cm-scroller { border-radius: 4px; } */`
> 
> It works in obsidian v1.3.7 , Latex suite 1.74/1.8.8

Thank you for the fix! I've included it in 1.8.9.
