### ISSUE TITLE
[FEATURE] Add snippet option to differentiate between 'inline' and 'display' math modes

### ISSUE THREAD

**Issue by SilverSlayer547** [artisticat1/obsidian-latex-suite#188]
Adding 't' to a snippet's options will make it only trigger when outside of math, while 'm' makes it trigger only while in math. However there is no differentiation between inline ($...$) and display ($$...$$) modes. It would be nice if the option was expanded to be able to allow a snippet to trigger only in one of those two modes.

**Comment by artisticat1** [comment]
Implemented in 1.8.0. You can use `n` for inline math and `M` for block math.
