### ISSUE TITLE
[BUG] Latex Suite won't Automatically Load User-defined Snips for New Created Note

### ISSUE THREAD

**Issue by Deeperand** [artisticat1/obsidian-latex-suite#190]
# Description

When turn on `Load snippets from file or folder`, and set my snip path (`obs_conf/custom_snippets.ts` for me), I found each time I create a new file, my customized snips didn't be loaded, and only the `Latex Suite` built-in snippets work. The solutions are either manually turn off and turn on `Latex Suite` -> `Enabled` option, or change my `custom_snippets.ts` and save it (I guess, perhaps, this is manually telling `Latex Suite` "wake up and load my snippets!").

# To Reproduce

- turn on `Load snippets from file or folder` in `Latex Suite`'s setting (my snips path is `obs_conf/custom_snippets.ts`);
- Create a new file by Obsidian command `Create new note`;
- then I found my snippets can' be used, only built-in snippets work (or equivalently, I suspect my customized snippets file didn't be loaded);
- turn off and turn on `Latex Suite` -> `Enabled` option, or change my `custom_snippets.ts` and save it (NOTE: the note must be opened at an active window. If it in the other tab but not opened, the user's snippets will also won't loaded for the note);
- my snippets can work

# Expected Behavior

Whenever I create a new note, the customized snippets should work (or equivalently, the customized snippets file should be loaded)

# Additional Info
Obsidian version: v.1.4.13
`Latex Suite` version: v.1.8.0

**Comment by artisticat1** [comment]
Thank you for the detailed report! Fixed in 1.8.1.
