### ISSUE TITLE
[BUG] Cannot insert newlines within indented math blocks

### ISSUE THREAD

**Issue by mzietlow** [artisticat1/obsidian-latex-suite#193]
# Description

With the latest updates (`v1.8.1` and `v1.8.0`) I am no longer able to insert new lines within indented math blocks. The issue does not seem to appear with `v1.7.4`.

# To Reproduce

- Create a new vault.
- Install and enable Latex Suite.
- Insert `- $$$$` (same with `> $$$$`).
- Try creating a new line `- $$\n$$`. (Doesn't work).
- Disable Latex Suite.
- Try creating a new line `- $$\n$$`. (Does work).

# Expected Behavior

I should be able to make a new line within indented math blocks:

``` md
> $$$$
```

should become

```md
> $$
> ...
> $$
```

# Additional Info

Furthermore, it is no longer possible to edit existing indented math blocks. Consider the following example:

```md 
> My mathblock
>
> $$
> asd
> $$
``` 

When I try to append `fgh` to `asd` as follows:

```md 
> My mathblock
>
> $$
> asd fgh
> $$
``` 

shortly after editing, the block will reset back to

```md 
> My mathblock
>
> $$
> asd
> $$
```

# Similar Issues

I also experience weird cursor jumps, which might related this issue to #192.

**Comment by artisticat1** [comment]
Fixed in 1.8.2.
