### ISSUE TITLE
[BUG] Obsidian hanging when opening certain notes on 1.8.2

### ISSUE THREAD

**Issue by joelatschool** [artisticat1/obsidian-latex-suite#196]
# Description
After upgrading to 1.8.2 opening certain notes (I cannot determine what the precise culprit is yet) causes Obsidian to effectively hang if the 1.8.2 version of Latex Suite is enabled (I have tested with 1.8.1 and it works fine).

# To Reproduce
Unfortunately I have not had time to find a minimal reproduction of this bug, although it occurs even with all other community plugins disabled.

# Expected Behavior
Obsidian to continue responding to inputs when the plugin is enabled and the problematic notes are opened.

# Additional Info

By playing around with the stepper in dev tools, I have found that this loop appears to be the culprit: https://github.com/artisticat1/obsidian-latex-suite/blob/3d38e66c8f22c344dc5b80d50a69d8f042191fa4/src/utils/editor_utils.ts#L124 and as such the bug was probably introduced with this commit:  a8ffddbcbecd7d2c6d22c5a5dd52e2db496c5c68

# Platform 

I am using Ubuntu 23.04, with Obsidian 1.4.13, packaged from Flathub.

**Comment by blueted2** [comment]
I've also been having issues, I think it has something to do with inline expressions, specifically empty ones #197.

**Comment by artisticat1** [comment]
Apologies for the bug, and thanks for narrowing it down to that loop. Should be fixed in 1.8.3.
