### ISSUE TITLE
[BUG] having an empty inline math expression causes freeze

### ISSUE THREAD

**Issue by blueted2** [artisticat1/obsidian-latex-suite#197]
# Description

Having an empty inline expression somewhere in a note causes obsidian to freeze.

# To Reproduce

Issue present on v1.8.2, but not on v1.8.1

Combinations tested:
- disable latex-suite, type '$$' in a note, re-enable plugin -> crash
- disable latex-suite, type '$ $' in a note, re-enable plugin, then remove space -> crash
- start with plugin enabled, type '$$' (or 'mk' snippet) -> crash

```
$$ -> crash
$ $ -> fine
$$$$ -> fine
```

# Platform

OS: linux-mint
Obsidian: 1.4.13

**Comment by blueted2** [comment]
It would seem that removing this line fixes the issue, although I'm nowhere near familiar enough with the code base to say whether this is a valid fix.
https://github.com/artisticat1/obsidian-latex-suite/blob/a8ffddbcbecd7d2c6d22c5a5dd52e2db496c5c68/src/utils/editor_utils.ts#L127C1-L127C1

**Comment by artisticat1** [comment]
Apologies for the bug. Should be fixed in 1.8.3.
