### ISSUE TITLE
[BUG] "Cannot read properties of null (reading 'name')" in 1.8.0+

### ISSUE THREAD

**Issue by joelatschool** [artisticat1/obsidian-latex-suite#198]
# Description
Any version 1.8.0+ or higher is refusing to open certain notes (again, sorry but I am not sure why this note in particular is causing issues) and instead throwing the following error:

```
app.js:1 TypeError: Cannot read properties of null (reading 'name')
    at isWithinInlineEquation (plugin:obsidian-latex-suite-less-old:6978:15)
    at Context.fromState (plugin:obsidian-latex-suite-less-old:6872:32)
    at getCursorTooltips (plugin:obsidian-latex-suite-less-old:8857:23)
    at e.create (app.js:1:331436)
    at Object.create (app.js:1:331544)
    at e.computeSlot (app.js:1:344603)
    at Sr (app.js:1:335544)
    at new e (app.js:1:341419)
    at e.create (app.js:1:344521)
    at t.set (app.js:1:1263215)
```

(Ignore `*-less-old`, that's just me trying to diagnose the issue by installing multiple versions of the plugin in the same vault).

# To Reproduce
Again, not sure how to reproduce the issue except that you need to enable a 1.8.0+ version of Latex Suite and then open a problematic note.

# Expected Behavior
The note to open and be readable and editable normally.

# Additional Info
The error is originating in this function:
https://github.com/artisticat1/obsidian-latex-suite/blob/3d38e66c8f22c344dc5b80d50a69d8f042191fa4/src/utils/context.ts#L177

Curiously, the file it is occurring in contains no math or even normal text, and includes entirely of tags, headings, and bullet lists of links to other notes.

 # Platform 

Obsidian v1.4.13, packed by Flatpak, on Ubuntu 23.04.

**Comment by artisticat1** [comment]
Thank you for the report! Can you let me know whether the issue still occurs in 1.8.3?
