### ISSUE TITLE
Plugin Usage (Questions about how to get started)

### ISSUE THREAD

**Issue by parkco34** [artisticat1/obsidian-latex-suite#20]
I apologize in advance if I'm not going about this correctly, but I'm having trouble even just implementing the instructions in the README file.  I have installed the plugin in my Obsidian Vault.  I 'm not sure how to actually start using it.  Is there a mode or something I'm missing?  I honestly am not even sure what question to ask.  

I typed 'dm' per instructions but nothing happens.  I've tried various things such as, typing the pair of '$' signs and double '$' signs, following along with the GIF provided and I am not seeing any results that resemble what is in the README.  

I'm sure I'm just missing something basic but I'm not sure what else to try and I need to be able to type up math notes quickly as possible.  Thank you!

**Comment by artisticat1** [comment]
Hi! If nothing is happening, it sounds like you might be using the legacy editor instead of the new Live Preview editor. (Let me know if this isn't the case.)

If so, try switching to Live Preview mode in Obsidian settings and see if that fixes things; the plugin doesn't support the legacy editor.

**Comment by parkco34** [comment]
That's it!  Thank you so much!

**Comment by artisticat1** [comment]
Great!

Did you see this warning pop up when enabling the plugin?

![image](https://user-images.githubusercontent.com/100622574/170790044-73ecbb1b-4118-4e98-9764-3597be9aef1e.png)

It's meant to let users know the plugin only works with LP. But maybe the pop up failed to show up, it doesn't last long enough for users to notice, or I need to modify the message asking the user to switch on LP.

**Comment by parkco34** [comment]
Yes I did.  Thank you.  I knew it was something silly I was missing
