### ISSUE TITLE
[BUG] None of the snippets will work inside ```

### ISSUE THREAD

**Issue by Rizumu85** [artisticat1/obsidian-latex-suite#202]
# Description
Snippets like dm, x/y any of those won't work inside of ```

# To Reproduce
Type
```
Then type something here for snippets and it won't work.

# Expected Behavior
It just output the word themselves like dm, x/y

# Additional Info
![image](https://github.com/artisticat1/obsidian-latex-suite/assets/25150828/b508edbb-b046-4553-9d39-ea40fb014125)
![image](https://github.com/artisticat1/obsidian-latex-suite/assets/25150828/2cb2130d-f830-4e67-9dda-c3676461e472)
![image](https://github.com/artisticat1/obsidian-latex-suite/assets/25150828/a5f274cd-b831-485f-99f0-eb075ed027ba)


<!-- # Platform -->
Windows 11

<!-- # Additional context -->
Using the Obsidian Column plugin that requires ``` to create columns.

**Comment by RyotaUshio** [comment]
Take a look at the documentation:
https://github.com/artisticat1/obsidian-latex-suite/blob/main/DOCS.md#options

**Comment by artisticat1** [comment]
This is intended, since math snippets shouldn't run when writing code. If you'd like your math snippets to run in code blocks, you can add the "c" option to them (see the docs linked by RyotaUshio).

**Comment by Rizumu85** [comment]
> Take a look at the documentation: https://github.com/artisticat1/obsidian-latex-suite/blob/main/DOCS.md#options

Thank you for clarification!

**Comment by Rizumu85** [comment]
> This is intended, since math snippets shouldn't run when writing code. If you'd like your math snippets to run in code blocks, you can add the "c" option to them (see the docs linked by RyotaUshio).

Ohh that's why, thank you for answering me concern.
