### ISSUE TITLE
[BUG] Frequent console errors whenever I click anywhere in the editor

### ISSUE THREAD

**Issue by wenlzhang** [artisticat1/obsidian-latex-suite#203]
# Description

Whenever I clicked anywhere in the note editor or use up/down arrows, I observe the following error messages in the console:

```
Uncaught RangeError: A selection needs at least one range
    at e.create (app.js:1:323375)
    at TabstopGroup.toEditorSelection (plugin:obsidian-latex-suite:7371:42)
    at isInsideATabstop (plugin:obsidian-latex-suite:7504:77)
    at handleUpdate (plugin:obsidian-latex-suite:8914:12)
    at e.update (app.js:1:487705)
    at e._dispatch (app.js:1:483944)
    at e.dispatch (app.js:1:485722)
    at app.js:1:1437617
```

Also, the cursor jumps up and down, making it not possible to navigate correctly in the note editor.

# To Reproduce

Click anywhere in the editor or use up/down arrows.

# Expected Behavior

No errors in the console, and one can navigate normally in the note editor.

# Platform

macOS 13.6; Obsidian 1.4.14; LaTeX Suite 1.8.3

**Comment by artisticat1** [comment]
I cannot reproduce this. Does the issue occur in all notes? Does it only occur after you trigger a certain snippet?

**Comment by wenlzhang** [comment]
> Does the issue occur in all notes? Does it only occur after you trigger a certain snippet?

It is strange that I do not see this issue now. But I will report back if it happens again. Thanks!
