### ISSUE TITLE
How to add snippet for norm \|

### ISSUE THREAD

**Issue by zcysxy** [artisticat1/obsidian-latex-suite#21]
Thanks for this amazing plugin!

I want add snippets for literal `\|` to `\\| $0 \\|` and literal `@\|` to `\\left\\| $0 \\right\\|`. However, I'm confused by the escaping rule. For literal `\|`, I tried `\|`, `\\|`, `\\\|` ... and seems none of these works.

I also tried regex, however, it didn't work either and wipe out the whole note.

**Comment by artisticat1** [comment]
```typescript
    {trigger: "@\\|", replacement: "\\left\\| $0 \\right\\|", options: "mA"},
    {trigger: "\\|", replacement: "\\| $0 \\|", options: "mA"},
```

works for me. I think it would be a good idea to add a default snippet for the norm symbol, so thanks!

**Comment by zcysxy** [comment]
Turns out it only works in the block math mode, I tested in the inline math mode so I thought it didn't work.

https://user-images.githubusercontent.com/48207708/170806660-3a3ac977-d733-485c-bcea-ebab2942c188.mov

**Comment by artisticat1** [comment]
I see. The problem is that in the text `$\$`, the backslash escapes the `$`, so it's treated literally. This means we're no longer considered to be in math mode, so snippets will not be run.

I think the best option here would be to use a different trigger, e.g. "norm" or "||".

**Comment by zcysxy** [comment]
Oh! You are right! I'll go with `||` and `@||`.
