### ISSUE TITLE
FR: suppose more LaTeX code in the conceal feature

### ISSUE THREAD

**Issue by YIRU69** [artisticat1/obsidian-latex-suite#22]
![image](https://user-images.githubusercontent.com/48148292/170948900-149d72c4-8685-4b88-a14e-a8b9edf1bb82.png)
![image](https://user-images.githubusercontent.com/48148292/170948962-416d277f-e43e-4ea1-ba10-8e0b4e351673.png)
Above the pic, suppose more latex code in the conceal feature
1. \lim\limits-->lim
2. \displaystyle{\frac{A}{B}}-->A/B
3. \sum\limits_{}-->$\sum$
4. \cdots -->...

**Comment by artisticat1** [comment]
Thank you for the suggestions!

Regarding `\frac{A}{B}`, it might be misleading if you've written e.g. `\frac{A}{B}C` which gets displayed as `A/BC`.

I'll try to handle `\limits`, `\displaystyle` and dots.

**Comment by YIRU69** [comment]
@artisticat1 Maybe try to add `()` just like `\frac{A}{B}C`-->`(A/B)C`.

**Comment by YIRU69** [comment]
![image](https://user-images.githubusercontent.com/48148292/170957653-bb9357e3-3f73-485a-93f5-6f0ac481bb7b.png)
Converted to `((A+B/C+D)/(a+b/c+d))`

**Comment by YIRU69** [comment]
I think that `\lim_{a \to b}` may to convert to same like `\sum`. Convert the `a \tp b` to subscript
![image](https://user-images.githubusercontent.com/48148292/170958918-44aaa02f-2b67-4807-b79b-e53ecca33ab6.png)

**Comment by artisticat1** [comment]
> @artisticat1 Maybe try to add `()` just like `\frac{A}{B}C`-->`(A/B)C`.

Yeah, I thought of that too. I wasn't sure about it though since `(A/B)C` implies there are brackets surrounding the fraction, like `(\frac{A}{B})C`, when there are none.

> ![image](https://user-images.githubusercontent.com/48148292/170957653-bb9357e3-3f73-485a-93f5-6f0ac481bb7b.png) Converted to `((A+B/C+D)/(a+b/c+d))`

That looks nice, however! I'll definitely give this a shot.

**Comment by artisticat1** [comment]
> I think that `\lim_{a \to b}` may to convert to same like `\sum`. Convert the `a \tp b` to subscript ![image](https://user-images.githubusercontent.com/48148292/170958918-44aaa02f-2b67-4807-b79b-e53ecca33ab6.png)

A problem with converting `a \to b` to subscript is that there is no unicode character for a subscript arrow. I can implement this by using e.g. `<sub></sub>` html tags instead, maybe in a future release.

**Comment by YIRU69** [comment]
`a` as subscript and `b` as superscript. Can it work?

**Comment by YIRU69** [comment]
This style may be adjusted. It's just the aesthetic aspect, I don't care it. And I really appreciate your plugin.
![image](https://user-images.githubusercontent.com/48148292/170962238-9d58ce15-6452-46b5-ba1e-2e3401493cc8.png)

**Comment by artisticat1** [comment]
> `a` as subscript and `b` as superscript. Can it work?

Yep, is this what you mean?
![image](https://user-images.githubusercontent.com/100622574/171003088-df39d193-3bee-45a6-8fd8-35f36007325b.png)

**Comment by YIRU69** [comment]
Correct! But I mean that make the `a` as subscript and `b` as superscript and `a`,`b` from `\lim_{a \to b} ` 
![image](https://user-images.githubusercontent.com/48148292/171004014-0b2a69b8-0331-41ec-a132-73f07086f46e.png)

**Comment by YIRU69** [comment]
@artisticat1 Hi, I find `displaystyle` still show on the new releases. Do you have other considerations?

**Comment by artisticat1** [comment]
Yes, I'll deal with `\displaystyle` in a future release! :)

**Comment by artisticat1** [comment]
Fractions are now concealed in 1.4.5.

<img src="https://user-images.githubusercontent.com/100622574/190901611-10cc6c86-ab69-49bd-b15a-0b7c8ce9f6c2.png" width=600>
