### ISSUE TITLE
Something in the snippet swaps ln  for \ln and it isn't in the snippet

### ISSUE THREAD

**Issue by candytripn** [artisticat1/obsidian-latex-suite#246]
### Discussed in https://github.com/artisticat1/obsidian-latex-suite/discussions/155

<div type='discussions-op-text'>

<sup>Originally posted by **Eneswar** May 31, 2023</sup>
Hey, something in the snippert turns "ln" into "\ln" and I have searched, manually looked for every single line but I have been unable to find it, can anyone help?</div>

**Comment by artisticat1** [comment]
Answered here: #155
