### ISSUE TITLE
[BUG] Space at the end of replacement string, is not recognized.

### ISSUE THREAD

**Issue by PhysicsInformedNoodle** [artisticat1/obsidian-latex-suite#247]
# Description
Space at the end of replacement string, like in "y ", is not recognized. What appears is "y" instead.

# To Reproduce
Use these as trigger:
```json
    {trigger: "x", replacement: "y ", options: "mA"},
```

# Expected Behavior
If we type `x` we expect it to be replaced with `y `, but instead it's replaced with `y`.

# Additional Info
1. The same issue is still present even with regex, ie with "rmA".
2. This bug mattered because I was interested in a snippet that activates when I press a space, maybe I the trigger `alpha ` to be replaced with `\alpha ` for instance, rather than `\alpha` which would force me to press space twice.

# Solution/Workaround
A single final space in replacement, gets turned into zero final spaces.
But two final spaces in replacement, get turned into one final space.
So for example the first snippet here doesn't work, but the second
```json
    // This doesn't work. "x" gets replaced "y".
    {trigger: "x", replacement: "y ", options: "mA"},
    // This fixes it. "z" gets replaced with "w ". Notice the two spaces in the replacement string below.
    {trigger: "z", replacement: "w  ", options: "mA"},
```

**This does not seem to work in regex mode, "rmA", though.**

**Comment by artisticat1** [comment]
Please see here: https://github.com/artisticat1/obsidian-latex-suite/discussions/222
