### ISSUE TITLE
In inline math, remove the space at the end of snippets

### ISSUE THREAD

**Issue by artisticat1** [artisticat1/obsidian-latex-suite#25]
In inline math, when a space is inserted before the closing dollar sign, the code is no longer read as a math equation. This causes snippets to stop working.

Solution: when a snippet is triggered in inline math, remove any spaces at the end of the `replacement`.

**Comment by artisticat1** [comment]
Added in 1.2.2

**Comment by RyotaUshio** [comment]
Just let me mention another solution: https://github.com/RyotaUshio/obsidian-inline-math

Using this plugin, you can keep staying in math mode while respecting the trailing whitespace.
