### ISSUE TITLE
`tab` key indents while in math mode

### ISSUE THREAD

**Issue by theodumont** [artisticat1/obsidian-latex-suite#26]
Hi,

Thank you for the great plugin!
On my computer, in math mode, the `tab` space still indents the line, instead of just going to the next cursor `$i`:

![tab](https://user-images.githubusercontent.com/59149044/172687380-e133c16a-7035-49af-a88c-8b7f9453ef0b.gif)

Here is my debug info, on the sandbox vault, where the issue still happens:

```
SYSTEM INFO:
	Obsidian version: v0.14.15
	Installer version: v0.12.19
	Operating system: Windows 10 Home 10.0.19043
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: none
	Snippets enabled: 0
	Safe mode: off
	Plugins installed: 1
	Plugins enabled: 1
		1: Latex Suite

RECOMMENDATIONS:
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the help vault or disable community plugins.
```

**Comment by artisticat1** [comment]
Unfortunately I'm unable to reproduce this, running the same Obsidian version and OS. Do you see any errors in the console?

**Comment by theodumont** [comment]
Yes, actually I do!

```
TypeError: this.currentTabstopReferences.at is not a function
    at SnippetManager.isInsideLastTabstop (plugin:obsidian-latex-suite:4780)
    at LatexSuitePlugin.handleCursorActivity (plugin:obsidian-latex-suite:5590)
    at eval (plugin:obsidian-latex-suite:5970)
    at t.update (app.js:1)
    at t._dispatch (app.js:1)
    at t.dispatch (app.js:1)
    at setSelections (plugin:obsidian-latex-suite:4431)
    at SnippetManager.selectTabstopReference (plugin:obsidian-latex-suite:4742)
    at SnippetManager.consumeAndGotoNextTabstop (plugin:obsidian-latex-suite:4805)
    at LatexSuitePlugin.handleTabstops (plugin:obsidian-latex-suite:5784)
Gs @ app.js:1
t.runCustomHandlers @ app.js:1
(anonymous) @ app.js:1
```

**Comment by theodumont** [comment]
Could it be linked to my version of the installer not being the latest one?

**Comment by artisticat1** [comment]
> Yes, actually I do!
> 
> ```
> TypeError: this.currentTabstopReferences.at is not a function
>     at SnippetManager.isInsideLastTabstop (plugin:obsidian-latex-suite:4780)
>     at LatexSuitePlugin.handleCursorActivity (plugin:obsidian-latex-suite:5590)
>     at eval (plugin:obsidian-latex-suite:5970)
>     at t.update (app.js:1)
>     at t._dispatch (app.js:1)
>     at t.dispatch (app.js:1)
>     at setSelections (plugin:obsidian-latex-suite:4431)
>     at SnippetManager.selectTabstopReference (plugin:obsidian-latex-suite:4742)
>     at SnippetManager.consumeAndGotoNextTabstop (plugin:obsidian-latex-suite:4805)
>     at LatexSuitePlugin.handleTabstops (plugin:obsidian-latex-suite:5784)
> Gs @ app.js:1
> t.runCustomHandlers @ app.js:1
> (anonymous) @ app.js:1
> ```

That's really helpful, thanks!


> Could it be linked to my version of the installer not being the latest one?

It might be! Apparently the `Array.at()` function was introduced to JavaScript relatively recently. Try updating and let me know if it works.

**Comment by artisticat1** [comment]
Great! ❤️ Apologies for the hassle. I'll see whether I can implement a warning when `Array.at()` is unavailable, or just use a different function altogether. Enjoy the plugin!

**Comment by theodumont** [comment]
No problem at all! I should have updated the installer right away. Thank you very much for the great plugin! I'm closing the issue.
