### ISSUE TITLE
Load packages into MathJax

### ISSUE THREAD

**Issue by Comprehensive-Jason** [artisticat1/obsidian-latex-suite#264]
# Description of the Problem
Certain packages in MathJax (e.g. physics, mathtools) are not autoloaded and need the user to explicitly add `$\require{package}$` into their Obsidian markdown files.

Doing so is annoying and behaves inconsistently due to how `\require` affects the entire vault upon loading, but stops affecting the entire vault upon restart.

For example, if I write the following Latex in Obsidian file A:

```
\require{physics}
\dv{x}{t}(y^2-5) \qquad \dv{x}{t} (y^2-5) \qquad \dv{x}{t}
```

If I then write the following immediately after in a different file B (forgetting to add `\require`), it will work perfectly fine:

```
\pdv{x}{t}{z}(y^2-5) \qquad \pdv{x}{t}{z} (y^2-5) \qquad \pdv{x}{t}{z}
```
Immediate result:
![image](https://github.com/artisticat1/obsidian-latex-suite/assets/68677082/0019af56-6006-4bc6-b35b-5ab4c05f6815)

However, if I restart Obsidian (thus clearing anything loaded previously using `\require` ) and then open file B, I will get an error:
![image](https://github.com/artisticat1/obsidian-latex-suite/assets/68677082/12e78216-298e-402a-8ac3-d1268dbbc5f5)

This becomes a huge pet peeve when you can't remember if you added `\require` to all the necessary files, especially since the `\require` command is invisible once you click off the Latex. 

# Description of the Solution

Latex Suite should provide a section where users can type in their preferred packages to `\require` for the entire vault. This section of Latex can simply be loaded upon startup in the background so said packages are always loaded immediately.

**Comment by artisticat1** [comment]
I consider this out of scope for this plugin; do either of these plugins solve your issue?

- https://github.com/wei2912/obsidian-latex
- https://github.com/RyotaUshio/obsidian-mathjax-preamble-manager

**Comment by Comprehensive-Jason** [comment]
wei2912 and RyotaUshio both are working solutions. RyotaUshio's shows extra promise because you can specify per-folder or per-note preambles, which in a roundabout way helps solve #58.
