### ISSUE TITLE
[BUG] Inline math popup issue with line wrap

### ISSUE THREAD

**Issue by Brenzle** [artisticat1/obsidian-latex-suite#275]
# Description

With math popup preview position set to "Below", when the equation gets long enough to wrap into two or more rows the popup obstructs the view.
# To Reproduce

- set math popup preview position to "Below"
- write inline math long enough that it wraps into multiple rows
# Expected Behavior

If set to "Below", popup should stay under the last row of the inline math section so that all the rows stay visible.

# Screenshots

Popup set to "Above":
(current workaround, but not a solution since I'd like to be able to see previous text)

![image](https://github.com/artisticat1/obsidian-latex-suite/assets/105920795/54f9ad27-f535-4cf6-a6b4-941ca5a809a9)

Popup set to "Below":

![image](https://github.com/artisticat1/obsidian-latex-suite/assets/105920795/6ce1a969-9302-4f04-b16b-5ab1633b6a24)

# Platform and versions

Windows 10
Obsidian v1.5.8
Latex Suite 1.9.1

**Comment by bdm-k** [comment]
The simplest way to solve this issue is to modify line 39 of math_tooltip.ts as follows.
```diff
- pos: (ctx.mode.inlineMath || settings.mathPreviewPositionIsAbove) ? bounds.start : bounds.end,
+ pos: settings.mathPreviewPositionIsAbove ? bounds.start : bounds.end,
```
However, this solution has one drawback: the tooltip position shifts every time a new symbol is typed.

**Comment by Brenzle** [comment]
I don't see that file in the `.obsidian\plugins\obsidian-latex-suite folder`

Where should I look for it?

**Comment by bdm-k** [comment]
https://github.com/artisticat1/obsidian-latex-suite/blob/09e5a2a700a8c63ede979e65d6ec5ecd8cb1910c/src/editor_extensions/math_tooltip.ts#L39

**Comment by Brenzle** [comment]
I see now, the popup follows the cursor, that's pretty annoying tho. I'll keep using the 'above' setting until there's a way to know in which line the cursor is, so the popup can be fixed to the start of that line. Thanks for the effort anyway!

**Comment by cruisermaxx** [comment]
Indeed, the popup preview block the text both above and below which is quite inconvenient~
