### ISSUE TITLE
[BUG] Incorrectly functioning "ll" snippet

### ISSUE THREAD

**Issue by Malachi-H** [artisticat1/obsidian-latex-suite#277]
# Description
Pressing lower case L twice in a row is replaced by "\ll" automatically. 
1. This is not referenced in the snippets file in the plugin settings.
2. This prevents other snippet activation such as "lll" (lower case LLL) converting to "\ell"
3. The snippet for "\ll" is already handled by "<<"

# To Reproduce
press "l" twice in a row inside of a math block with a default installation of the plugin

# Expected Behavior
Pressing "ll" should not activate any snippet. 

# Additional Info
Using a Windows 11 operating system.
Obsidian Version: 1.5.11 (Latest)
Latex Suite Version: 1.9.1 (Latest)

Imgur videos demonstrating the problem and fix through altering the code in main.js:
[Link](https://imgur.com/a/qLn1G1H)

Same videos hosted on GitHub:
The Issue:
https://github.com/artisticat1/obsidian-latex-suite/assets/67351403/3e146f23-e3f2-4748-98b7-4fba2e931c68
The Fix:
https://github.com/artisticat1/obsidian-latex-suite/assets/67351403/0ccbf950-a913-449b-99d3-5fb863794587
After Fix:
https://github.com/artisticat1/obsidian-latex-suite/assets/67351403/2e42dfe4-2bfa-4cb4-918a-40f832be63c0

**Comment by artisticat1** [comment]
There's no need to modify `main.js`; you can simply edit the snippet variables in the plugin settings, under Advanced snippet settings > Snippet variables.

I'll try to make this clearer!
