### ISSUE TITLE
[FEATURE] ignore a snippet if it is preceeded by an alphabet

### ISSUE THREAD

**Issue by dead-summer** [artisticat1/obsidian-latex-suite#278]
# Description of the Problem
The plugin will not ignore a snippet if it is preceeded by an alphabet. 

# Description of the Solution
eg. "re" is the shorthand for "\mathrm{Re}". But when typing "\varepsilon" I really want will  trigger the replacement. 
Such automatic replacement is very troublesome, can you make the automatic replacement of the snippet be cancelled when there are other letters before it.
ie. typing "\varepsilon"  will **NOT**  trigger the replacement "re".

# Additional
The plugin is swesome and I really like it and need it. I hope that the problem will eventually be resolved. If this issue exists or has been resolved, please forgive my oversight.

**Comment by artisticat1** [comment]
This can be done with the "w" snippet option ([see the docs here](https://github.com/artisticat1/obsidian-latex-suite/blob/main/DOCS.md#options)).
