### ISSUE TITLE
BUG: in the one-line mode, some letters will disappear.

### ISSUE THREAD

**Issue by aoout** [artisticat1/obsidian-latex-suite#28]
For example, set replacement to `\Leftrightarrow`, and input the trigger in the `$ context $`, and the result is `\$\Leftrightarrw\$`.
The letter "o" will disappear.

**Comment by artisticat1** [comment]
I can't reproduce this:

https://user-images.githubusercontent.com/100622574/173190533-e6871dc4-6735-4a55-8d16-3f80ccf14a47.mp4

Can you paste your debug info (Command palette -> Show debug info) here? Do you see any errors in the console (`Ctrl + Shift + I`)?

**Comment by artisticat1** [comment]
Nevermind, I reproduced it. I'll fix it in 1.2.3
