### ISSUE TITLE
[FEATURE] Disable snippet expansion when IME is on

### ISSUE THREAD

**Issue by RyotaUshio** [artisticat1/obsidian-latex-suite#284]
Thank you for maintaining this important plugin for all who do math in Obsidian. I have a suggestion which will be beneficial for those who use IME.

# Description of the Problem

When I type "Vimキー" (which means "Vim keys" in Japanese), the keystroke looks like this:
```
Shift+V, i, m, (Turn on IME), k, i, -, (space to convert hiragana to katakana)
```
Then, the `m` before turning on the IME and `k` after that triggers the default `mk` snippet, and it results in the following, which is unwanted:
```
Vi$きー$
```

# Description of the Solution

I think this problem can be eliminated by disabling expanding snippets while IME is on, i.e. when [view.composing](https://codemirror.net/docs/ref/#view.EditorView.composing) is `true`.

# Additional

None

**Comment by artisticat1** [comment]
Hi, thanks for raising an issue!

Issues relating to IME input have been raised in the past (#52, #213, #191). However, I have little knowledge of IME input methods and no easy way to test/debug a solution.

From your other plugins, it looks like you're familiar with CodeMirror. If you're able/willing, I'd happily accept a PR solving this issue! (If so, there's some discussion in the previously linked issues that may be of relevance.)
