### ISSUE TITLE
Suggestion for Enhancement: Auto-Suggest whole Equations

### ISSUE THREAD

**Issue by BananenRitter** [artisticat1/obsidian-latex-suite#289]
# Usecase:
Im a beginner and sure i can invest a lot of time to learn the basics but it would be much easier to use autocompletion of generic examples and fit them together.
To create a library by myself also seems too tome consuming if you think about that thousands of students have to do this. The time they waste writing basic stuff could be invested in actually solving equations.

# How does it work?
- Suggests whole Equations by:
1. using specific hotkey
2. or typing specific symbol combination
3. or Typing $, $$

- Suggestions are displayed below the currently active line.
- Occupies 3 rows vertically
- **First row** for the name of the Equation
- Shows the Suggestions 2 Times **vertically**:
1. **Second row:** As LaTeX Text
5. **Third row:** As rendered LaTeX Equation

- Search Equation by Name
- Search Equation by Major/ Topic

## Settings:
- Amount of Suggestions that are displayed at the same time **Horizontally** Values: 0-3, Standard: 1

**Comment by artisticat1** [comment]
This is out of scope for this plugin. You may be interested in #113.
