### ISSUE TITLE
mA mode not working

### ISSUE THREAD

**Issue by faro1219** [artisticat1/obsidian-latex-suite#29]
I created a new Obsidian vault and installed the latex suite. I found only tA mode works and mA mode is not working.

**Comment by faro1219** [comment]
![image](https://user-images.githubusercontent.com/31923679/173685617-75eb406b-258d-448a-88f3-b37d785dea57.png)

**Comment by faro1219** [comment]
![image](https://user-images.githubusercontent.com/31923679/173690980-a322ac71-2447-4001-84f7-1e8e108d6534.png)

**Comment by artisticat1** [comment]
Thank you! This is caused by using an old version of the Obsidian installer. Should be fixed in 1.2.4.
