### ISSUE TITLE
[FEATURE] Shortcut for "\\" symbol in gather environment

### ISSUE THREAD

**Issue by nowaylifer** [artisticat1/obsidian-latex-suite#294]
# Description of the Problem
Gather environment doesn't have any shortcuts.

# Description of the Solution
Would be great if pressing `Enter` inside gather environment would insert "\\\\" symbol and move cursor to a new line, like in align environment.

**Comment by llakala** [comment]
I was confused as to why this wasn't working, when I realized that I just hadn't enabled `gather` in the list of matrix shortcuts. Maybe it could be there by default?
