### ISSUE TITLE
[DOCS] Vertical and diagonal ellipses in matrices

### ISSUE THREAD

**Issue by borenstein** [artisticat1/obsidian-latex-suite#311]
# Description

When I am creating a matrix in my notes, I almost always need `\vdots` and `\ddots`. But when I try to type either of these in while using Latex Suite, eager substitution turns it into, e.g., `\\ddot{s}`.

I tried to fix this by adding snippets for `vdots` and `ddots`, but these interfere with the existing snippets, resulting in additionally problematic behavior.

The only solution I've found so far is to disable the plugin and then re-enable it. I'm sure there is a correct way to do it, but I can't figure out what it is.

# Importance

This is a fundamental piece of functionality, without which the plugin most definitely does not let me type math as fast as I can handwrite it, or even as fast as I can type it without the plugin. Given the 150,000 users of the plugin, I'm absolutely certain there must be a way to do this, but I don't know what it is.

**Comment by artisticat1** [comment]
Yes, this seems like an oversight with the current default snippets.

Some ideas to solve this:

- Create a snippet that maps `\dot{v}s` to `\vdots`, so that entering the keystrokes <kbd>v</kbd><kbd>d</kbd><kbd>o</kbd><kbd>t</kbd><kbd>s</kbd> will produce `\vdots`.
- Disable the `ddot` snippet. Create a snippet that maps `\dot{d}s` to `\ddots`.
- Create snippets with entirely new triggers that map to `\vdots` and `\ddots`.

**Comment by borenstein** [comment]
Thank you! I like the idea of disabling `ddot` and then creating new `ddots` and `vdots` snippets. I tried to figure out how to do this, but I admit that I'm a little confused about how to reason around the snippets, because it seems like there must be some kind of execution priority. Could you please tell me what changes to make? Thank you for your patience.

**Comment by artisticat1** [comment]
```typescript
{trigger: '\\dot{d}s', replacement: '\\ddots', options: 'mA'},
{trigger: '\\dot{v}s', replacement: '\\vdots', options: 'mA'},
```

should work if you're looking to implement my first two suggestions.

**Comment by borenstein** [comment]
🙌 Bravo!!
