### ISSUE TITLE
[BUG]: Latex Suite makes Obsidian slow and laggy 

### ISSUE THREAD

**Issue by ianTevesAcc** [artisticat1/obsidian-latex-suite#315]
Latex Suite is an amazing plugin that speeds up typing math notes, but unfortunately it also slows down obsidian massively for me. I've turned off every setting in the plugin settings pane to find out whats taking so much of obsidian resource, but unfortunately just having the plugin enabled slows down obsidian by itself. Can I have some help in order to circumvent this problem? Latex Suite is way too essential for me to give up on.

# To Reproduce
1. Install and activate Latex Suite.
2. Open a note and press enter to enter multiple new lines successively.

# Expected Behavior
New Lines to be entered smoothly.

# Actual Behavior
Slow and laggy insertion of new lines. (If you're using a better computer, you may need to use a larger math note / large note vault).

Windows Specifications
- Edition	Windows 11 Home
- Version	24H2
- Installed on	‎4/‎11/‎2024
- OS build	26120.961
- Experience	Windows Feature Experience Pack 1000.26100.8.0

Device Specifications
- Processor	11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz   2.80 GHz
- Installed RAM	16.0 GB (15.8 GB usable)
- System type	64-bit operating system, x64-based processor
- Manufacturer    Acer

**Comment by artisticat1** [comment]
Hi - this is surprising because I've never seen performance issues reported before.

- Can you reproduce this in the sandbox vault, with only Latex Suite enabled?
- Does the issue occur when using the default snippets?
- Can you provide a sample of a large math note for testing?

**Comment by ianTevesAcc** [comment]
@artisticat1 
Thank you for the reply. Sorry I missed out on some key points on my issue.
Latex Suite runs perfectly on a fresh off the boat vault with just itself running. But when run in parallel with other plugins, latex suite is what pushes Obsidian to the edge and crashes. 

You can see this in action in the following, where when Latex Suite is off, Obsidian is pretty fast. When Latex is on, Obsidian is slow.
![record_2024-07-14_00-39-54](https://github.com/user-attachments/assets/0819d97e-b9e5-4ee7-bd62-6da88c0c7bea)

Latex Suite is great if I were to just keep 10 plugins. But I would like to keep my other cosmetic plugins too 😅

Honestly it would be amazing if I could just toggle latex suite on or off to when Im only typing math / when ever I need it, by using a hotkey. As I dont really need to navigate my note when Im writing math. But of course that would only benefit me and not the wider community. Therefore makes me question the need of such work.

**Comment by ianTevesAcc** [comment]
I found out that the plugin `Iconize` when run with `Latex Suite` drastically decreases OB performance. 
I switched `Iconize` with `Iconic` instead.
