### ISSUE TITLE
Can't load plugin since 0.15.0 (Insiderbuild)

### ISSUE THREAD

**Issue by Pummelfisch** [artisticat1/obsidian-latex-suite#33]
Since the update to the new insiderbuild 0.15.0 or 0.15.1 the plugin can't be loaded anymore for me. I assume it has to do with the update to Codemirror 6, but I don't know.

By the way, I'm loving this plugin. It made writing so much faster and more fluid for me. So thank you very much ☺

**Comment by artisticat1** [comment]
Yes, the new CM6 update breaks the plugin! However, I don't have access to insider builds, so I can't test and update the plugin on version 0.15 yet.

I'll release an update as soon as I can after v0.15 is made available to the public. Glad you're enjoying the plugin :)

**Comment by artisticat1** [comment]
I was gifted an insider license and have now updated the plugin for v0.15!
