### ISSUE TITLE
Better Concealing

### ISSUE THREAD

**Issue by vreithinger** [artisticat1/obsidian-latex-suite#35]
First of all let me thank you for this awesome plugin. I have a few questions regarding the concealing of the latex code

1. I noticed that \overline{x} does not render to x̄. In fact, only very few overlined letters (i suspect the ones who have a single unicode letter corresponding to it) render in the concealed mode. It should be theoretically possible to render every possible overlined character as unicode is stackable (so even greek ones and fat ones and so on). Same goes for dotted / double dotted / hat and so on.
2. is it possible to have \frac{a}{b} simply render to a/b? If the fraction is larger it could render with brackets like {...}/{...}
3. A little thing: is it possible to have \\, and \\: and \\; just render to [space]? I think it would make the concealed view even easier to read

**Comment by artisticat1** [comment]
> only very few overlined letters (i suspect the ones who have a single unicode letter corresponding to it) render in the concealed mode. It should be theoretically possible to render every possible overlined character as unicode is stackable (so even greek ones and fat ones and so on).

Yes, that's correct! Only letters that have a corresponding unicode character with a bar get concealed. I'll look into stacking unicode characters; I wasn't aware that overlines etc were stackable. Thank you for the tip!

> 2. is it possible to have \frac{a}{b} simply render to a/b? If the fraction is larger it could render with brackets like (...)/(...)

Yep, I can try to add this in a future version. There's some discussion of this in #22.

> 3. A little thing: is it possible to have \, and \: and \; just render to [space]? I think it would make the concealed view even easier to read

Good idea, I'll add this in the next release.

**Comment by vreithinger** [comment]
Thank you so much for the fast reply! Sounds good, im looking forward to the next release :)

**Comment by artisticat1** [comment]
Fractions are now concealed in 1.4.5.

<img src="https://user-images.githubusercontent.com/100622574/190901611-10cc6c86-ab69-49bd-b15a-0b7c8ce9f6c2.png" width=600>

**Comment by thudjx** [comment]
> Fractions are now concealed in 1.4.5.
> 
> <img alt="" width="600" src="https://user-images.githubusercontent.com/100622574/190901611-10cc6c86-ab69-49bd-b15a-0b7c8ce9f6c2.png">

What theme are you using? The concealed code are quite wired in my case, and I thingk maybe this is caused by the theme.

**Comment by artisticat1** [comment]
> What theme are you using? The concealed code are quite wired in my case, and I thingk maybe this is caused by the theme.

This is the default theme in Obsidian v0.15. Can you share a screenshot showing the problem and the LaTeX source code behind it?

**Comment by thudjx** [comment]
> Can you share a screenshot showing the problem and the LaTeX source code behind it?
![image](https://user-images.githubusercontent.com/32637321/194756399-5eb6a3da-0e1d-484c-8eb3-ef8697d35044.png)
The powers in the first line is written as `^{2}` while in the second line `^2`.

**Comment by artisticat1** [comment]
Moving to a new issue (#62).
