### ISSUE TITLE
Can we have a separate file to save our settings?

### ISSUE THREAD

**Issue by faro1219** [artisticat1/obsidian-latex-suite#39]
In vscode or vim, we have latex.snip to save all our settings. Right now, all the settings are within the plug-in setting. I am wondering if we could have a separate file. Then, we can use vscode or sublime to edit it. This will be much more efficient.

**Comment by artisticat1** [comment]
Yes, I can consider adding this in a future release!

I've tried to make the snippets editor as usable / close to an IDE as possible. It contains syntax highlighting, line numbers, keyboard shortcuts, etc., so should be good enough for most purposes. Just wondering which features in vscode / sublime you're missing?

**Comment by faro1219** [comment]
Wow, that's an ambitious idea. To be honest, I think editing with Vscode is enough for me.  Right now, I think the most important feature in Vscode and sublime is search and replace. 

Besides, I meet some bugs recently. I was trying to type \otimes and \varphi in Latex. But I always get \o\times and \var\phi. I cannot find any options to stop the auto completion. Do you have any idea?

**Comment by artisticat1** [comment]
I'll try to issue a fix for those issues today.

**Comment by artisticat1** [comment]
Search and replace is available if you press Ctrl+F.

**Comment by faro1219** [comment]
> Search and replace is available if you press Ctrl+F.

Cool! Can we have a pop-out window for the editor? Right now, we can only see very few lines of the settings.

**Comment by faro1219** [comment]
> 



> `\otimes` and `\varphi` are fixed in the next release. In the meantime you can create snippets for `\otimes` and `\varphi`, and place them at the top of your snippets or give them a higher priority.

Thanks! May I ask what snippets lead to the bug? I didn't find any snippets related to it.

**Comment by artisticat1** [comment]
> Can we have a pop-out window for the editor? Right now, we can only see very few lines of the settings.

Ah, I see. This is out of scope at the moment, but any PRs to add this or the ability to save snippets in a separate file are welcome!

> Thanks! May I ask what snippets lead to the bug? I didn't find any snippets related to it.

The issue was that [`varphi` wasn't in the list of greek letters, and `times` appeared before `otimes` in the list of symbols](https://github.com/artisticat1/obsidian-latex-suite/commit/5cd9f0c41a4585bc272a96f7e2712eaff0fb4042). This meant "times" was matched before "otimes".

However `otimes` works on my machine even `times` is placed before `otimes`, so I'm not sure what's going on here.

**Comment by zcysxy** [comment]
I second this. Even though the embeded editor of this plugin is the smoothest one of all plugins I've used, but I think a great advantage of storing the config in a separate file is that we can backup and read the config more conveniently.

I know these two plugins store the config in a separate file:

* [Extended MathJax](https://github.com/xldenis/obsidian-latex)
* [vimrc-support](https://github.com/esm7/obsidian-vimrc-support)

If this feature gets supported, it would be even better if we can specify the config file location XD

**Comment by artisticat1** [comment]
Sounds good! Thanks for linking those plugins, I'll have a look at them for reference. I'll definitely include an option to select where the config is stored!

**Comment by mscott99** [comment]
I like this. It would also enable sharing of config files through github. This could be massive because the useful snippets vary depending on your field.

**Comment by loune20** [comment]
Seconding this, it could be very useful, especially to use the same snippets on mobile (plugin settings don't always sync) or on different vaults !  Also thanks a lot for the plugin, it's awesome !

**Comment by artisticat1** [comment]
Added in 1.6.0!

**Comment by zcysxy** [comment]
Hi @artisticat1, thanks for implementing this feature! It works like a charm. A small additional fr on this: could it read the settings file in a hidden directory like `.config/`?

**Comment by artisticat1** [comment]
> Hi @artisticat1, thanks for implementing this feature! It works like a charm. A small additional fr on this: could it read the settings file in a hidden directory like `.config/`?

Sure, open a separate issue and I can look into this!
