### ISSUE TITLE
Question: Why \le, \ge, \ne are excluded from conceal

### ISSUE THREAD

**Issue by zcysxy** [artisticat1/obsidian-latex-suite#41]
I use `\le`, `\ge`, and `\ne` since they are shorter than `\leq`, `\geq`, and `\neq`. But I found that these commands are excluded from the conceal list 😢

**Comment by artisticat1** [comment]
Oh whoops, I didn't know `\le`, `\ge`, and `\ne` were actual symbols and they were causing issues with `\leq`, `\geq`, and `\neq` so I commented them out of `conceal_maps.ts`. Will fix for next release!

**Comment by zcysxy** [comment]
Haha yeah, they are different names for the same objects.

**Comment by artisticat1** [comment]
Fixed in 1.4.2.
