### ISSUE TITLE
Feature Request: Math editor syntax highlighting themes

### ISSUE THREAD

**Issue by Pipluppp** [artisticat1/obsidian-latex-suite#45]
I've seen that the demo gifs from the README had a different color syntax highlighting compared to the original one from Obsidian. I am not sure if this can be integrated into the plugin, or if there is already some other plugin for this.

**Comment by artisticat1** [comment]
Some themes (e.g. Minimal, Primary, Sanctum) re-color the syntax, so you could try that.

In the demo gifs, I'm also using the [Dynamic Highlights](https://github.com/nothingislost/obsidian-dynamic-highlights) plugin to recolor some syntax (e.g. I made `\frac` green and `\partial` yellow).

Do these suit your needs?

**Comment by Pipluppp** [comment]
Thank you for the clarification! Did not realize that the themes I've been using were able to change syntax coloring, and I think those are enough for my issues.

I apologize if this is no longer directly related to the problem, but I was aiming to mimic the color syntax from this specific demo gif you had; would you mind sharing the themes you used, or the further changes you've made in this specific gif? These are one of the best math syntax coloring I've seen so far.

![image](https://user-images.githubusercontent.com/70219682/182036480-b0518020-6841-489b-938a-d403fc858738.png)

**Comment by artisticat1** [comment]
Sure thing!

The theme in the demo gif is Minimal. I used Dynamic Highlights to make `\frac` green and `\mathbf` purple. Lastly, for grey brackets, you should disable the "Color matching brackets" feature.

**Comment by Pipluppp** [comment]
Thank you for the help!
