### ISSUE TITLE
Bracket close as alternative to tab

### ISSUE THREAD

**Issue by mscott99** [artisticat1/obsidian-latex-suite#46]
When within an environment, make typing the correct closing bracket behave like tab. That is, in the case “(blabla[cursor])” then typing “)” moves the cursor out, the same as typing [TAB].

To be clear, I like the tabout behaviour, but sometimes I forget it and make a mistake, and then I have to erase the extra closing bracket. This would also match the behaviour of code editors.

I think this would be a good feature. Let me know!

**Comment by artisticat1** [comment]
Ah this is a bug, I'll fix it in one of the next releases.

**Comment by artisticat1** [comment]
I've solved this in 1.4.4.

**Comment by mscott99** [comment]
Thank you!
