### ISSUE TITLE
extend conceal map

### ISSUE THREAD

**Issue by VSAbramov** [artisticat1/obsidian-latex-suite#48]
Hello! Thank you for this great plugin, I love it!
I like using \geqslant and \leqslant instead of \geq and \leq, but it seems they are missing from the table, I'm getting ≤slant instead of just ≤. 
I believe in the future somebody will find some symbol that she wants to be concealed, what is best way to add a new symbol?

**Comment by artisticat1** [comment]
Hello! I can add `\geqslant` and `\leqslant` in the next release.

The best options for users wanting to add new symbols would be to either

- open an issue here on GitHub, or
- add the symbol themselves in [conceal_maps.ts](https://github.com/artisticat1/obsidian-latex-suite/blob/main/src/conceal_maps.ts) and open a PR.

**Comment by VSAbramov** [comment]
Thank you!

**Comment by artisticat1** [comment]
Added in 1.4.4.
