### ISSUE TITLE
Temporarily disable shortcut

### ISSUE THREAD

**Issue by matteosantama** [artisticat1/obsidian-latex-suite#54]
Is there a way to turn off the shortcuts momentarily? I am trying to write the word "admit" and the "dm" keeps triggering math mode.

**Comment by artisticat1** [comment]
Yes, you can run the "disable/enable all features" command from the Command Palette.

You can fix the problem with the "dm" snippet by adding the "w" word boundary option to it:

```typescript
{trigger: "dm", replacement: "$$\n$0\n$$", options: "tAw"},
```
