### ISSUE TITLE
Add snippet options for inline and block math

### ISSUE THREAD

**Issue by fenjalien** [artisticat1/obsidian-latex-suite#56]
I want a way to change how a snippet behaves depending on if its triggered in an inline math block ($$) or a normal math block ($$$$). 
A notable usage would in snippets for fractions. When in a normal math block I want the `frac` function to be used, however when in an inline math block I want the `flatfrac` function to be used.
I would guess that this can be achieved by adding a new option symbol, something like `i` or `M`.

btw I've come from the quick latex plugin and I'm blown away by how well this works, great work :)

**Comment by artisticat1** [comment]
Hello, glad you're liking the plugin :)

Sounds good, I can add two new snippet options for inline and block math.

**Comment by artisticat1** [comment]
Implemented in 1.8.0. You can use `n` for inline math and `M` for block math.
