### ISSUE TITLE
Change undo behaviour

### ISSUE THREAD

**Issue by XintakXVI** [artisticat1/obsidian-latex-suite#57]
Is there/could there be an option to make undo just reverse a snippet _expansion_, rather than undo everything up to before the snippet trigger was present?
As an example, typing `a` `/` expands to `\frac{a}{}`, and undoing reverts to just `a`. Could there be a setting to adjust the behaviour and make undoing revert to having the `a/`, just before the snippet expanded?

Thanks!

**Comment by artisticat1** [comment]
Good idea! It's definitely possible, I can add it in a future release.

**Comment by XintakXVI** [comment]
Thanks! Looking forward to it!

**Comment by artisticat1** [comment]
Done in 1.5.2.
