### ISSUE TITLE
Submission to community plugins

### ISSUE THREAD

**Issue by artisticat1** [artisticat1/obsidian-latex-suite#6]
Hi @tth05,

Thanks for writing the Completr plugin! I wrote this plugin that builds on your snippets with placeholders code. Just wondering whether you're OK with me sharing this with others and submitting it to the community plugins list? I've given you acknowledgement in the readme.

Have a great day! :)

**Comment by tth05** [comment]
Yeah sure, go ahead! Glad I could save someone the pain of figuring this out. Wouldn't even be necessary if CodeMirror snippets supported nesting :/

**Comment by artisticat1** [comment]
> Glad I could save someone the pain of figuring this out.

Absolutely, haha.

> Yeah sure, go ahead!

Great, thanks! 👍
