### ISSUE TITLE
Latex auto assume typing context/command

### ISSUE THREAD

**Issue by smerkousdavid** [artisticat1/obsidian-latex-suite#60]
I have this current issue of trying to type out a partial with respect to multiple variables
for example $\frac{ \partial^{2} f }{ \partial x \partial y }$ however if I try typing partial it obviously runs the first order partial snippet. I thought of starting the command \partial but that just does \ + ... first order partial snippet + tial.

I think it would be amazing to have the functionality of ignoring snippets if you start typing a command with a backslash. For example. I need to write \top a lot, but it usually converts to \to p and I can have a snippet to replace \to p with \top but it might make more sense if someone is starting to type with a \ that snippets do not run.

Do you have an idea on how to implement this, since I doubt you could just "split" the strings by space and see if you already start with a space and a backslash since many snippets/latex doesn't have it.

Thoughts?

**Comment by smerkousdavid** [comment]
A current idea would be to have a flag of when you encounter a backslash you ignore all further matching until one of the following.
1. space is hit
2. a number is typed
3. exiting of math mode?
4. change of cursor location?
I guess simply put any event after a \ that is not [a-zA-Z]

I have never written an obsidian plugin so don't know what the events/processes look like.

**Comment by proItheus** [comment]
Currently, you can try to add an option "w" to corresponding snippets, in this case the partial snippet, and then delete the latter "\" from word delimiters . All these could

**Comment by artisticat1** [comment]
You can achieve the behaviour of ignoring a snippet when there is already a `\` by using regex.


You can write a regular expression to match triggers that do not start with `\`. See [this snippet](https://github.com/artisticat1/obsidian-latex-suite/blob/247f9750bf662a7abb80585bbbff01f6012aa6b4/src/default_snippets.ts#L46) for reference. It automatically prepends a `\` to greek letters only if a `\` is not already there.

```typescript
{trigger: "([^\\\\])(${GREEK}|${SYMBOL})", replacement: "[[0]]\\[[1]]", options: "rmA", description: "Add backslash before greek letters and symbols"},
```

**Comment by artisticat1** [comment]
As of 1.5.2, by default, the "par" snippet must now be triggered using the Tab key.

Let me know if you encounter any problems using regex to ignore snippets when there's already a `\`.
