### ISSUE TITLE
[BUG?] Snippet replacement auto trim whitespace

### ISSUE THREAD

**Issue by proItheus** [artisticat1/obsidian-latex-suite#61]
When the `replacement` field in a snippet have some trailing whitespaces, it will be trimed when expanded. `\\forall...` will become `\forall` etc.(whitespace denoted as `.`).

I don't know if it's intended behavior, but it makes sense to let users decide whether they want a trailing space, right? My use case is to let `fa.` auto expand to `\forall.` (whitespace denoted as `.`). 

Edit: It seems that this only happens in inline math.

**Comment by artisticat1** [comment]
This is done on purpose so that triggering a snippet in inline math doesn't cause you to exit math mode. See #25.

**Comment by proItheus** [comment]
What about adding a zero-width char like `\u200b` or `\hspace{0pt}` before the last `$` in mk snippet? 
e.g.
`{trigger:"mk",replacement:"$$0\\hspace{0pt}$$1",options:"tAw"}`
Then we can safely allow trailing spaces in inline math .

Or maybe adding an option to disable auto trim space in inline math?

**Comment by artisticat1** [comment]
I don't like the idea of polluting users' code with zero-width characters (at least, not by default!). But yeah, the code should probably check whether the cursor is at the end of the equation before running auto-trim.

> Or maybe adding an option to disable auto trim space in inline math?

Sure, it can be considered for a future release! Any PRs are also welcome.
