### ISSUE TITLE
Conceal output looks strange

### ISSUE THREAD

**Issue by artisticat1** [artisticat1/obsidian-latex-suite#62]
@thudjx reports in #35:

The concealed code are quite wired in my case, and I thingk maybe this is caused by the theme.

![image](https://user-images.githubusercontent.com/32637321/194756399-5eb6a3da-0e1d-484c-8eb3-ef8697d35044.png)

The powers in the first line is written as `^{2}` while in the second line `^2`.

**Comment by artisticat1** [comment]
I see "j"s in the code. Does your equation have any "j"s? Can you share the source code for the entire equation?

**Comment by thudjx** [comment]
> I see "j"s in the code. Does your equation have any "j"s? Can you share the source code for the entire equation?
```latex
\begin{align} 
\dot{x}^{2}+\dot{y}^{j}=2 \\
\dot{x}^2+\dot{y}^j=2
\end{align}
```
I have tried using the default theme, and thing look much better:
![image](https://user-images.githubusercontent.com/32637321/194764678-9b49b4f1-20a5-43ae-838b-7b68962af6a3.png)

**Comment by artisticat1** [comment]
OK, I'll try fixing this in the next release. Which theme were you using before?

**Comment by thudjx** [comment]
Thank you so much!
I was using `blue topaz`. By the way, is there necessarity to put up an issue in that project?

**Comment by artisticat1** [comment]
I can't reproduce this issue using Blue Topaz:

<img src="https://user-images.githubusercontent.com/100622574/194767255-4ecf2ea1-81f3-42de-a14f-1a23e595d59a.png" width=300>

Also, the top row (using `^{2}`) is actually the row with the intended behaviour.

The bottom row (`^2`) is using an old approach; it seems I forgot to update it.

Are you able to use Inspect Element on the large green "2" and "j" to figure out where something strange is happening?

> By the way, is there necessarity to put up an issue in that project?

Perhaps we should wait to open an issue over there until we figure out whether the issue is on our end!

**Comment by thudjx** [comment]
It seems that I have changed the fontsize of mathjax code to be smaller in a snippet:
```css
:root{
  --font-size-latex: 0.95em;
}
```
And if I comment this out, everything looks normal.
I do this because the mathjax code is too big for a long formula, which doesn't bother me any more thanks to auto-concealing.

**Comment by artisticat1** [comment]
Great! I'll close this issue then.
