### ISSUE TITLE
[Feature Request] Can we define variables like $SYMBOL?

### ISSUE THREAD

**Issue by LingrenKong** [artisticat1/obsidian-latex-suite#63]
Thank you for building this awesome plugin. This plugin works pretty well and helps me to use latex.

I'm trying to build my own snippets, and the idea of $symbol variable can make snippet more elegant. Is it possible to define more variable and edit exist $symbol?

here's some example to show the importance of variable editing:

- `ll` is included in $symbol, which cause default snippet `lll` failed
- symbols can be set to different category, `times` need auto spacing, but  `leq` sometimes need auto subscript

**Comment by artisticat1** [comment]
Good idea, I can add this to a future release.

**Comment by LingrenKong** [comment]
thank you

**Comment by mayurankv** [comment]
I'd also love this. Thanks for all your work!
