### ISSUE TITLE
Load the snippet from the file system

### ISSUE THREAD

**Issue by thudjx** [artisticat1/obsidian-latex-suite#64]
Is it possible that we define the snippet in a file rather than in the setting directly, so that it can be easily maintained?

**Comment by windily-cloud** [comment]
I think it's good enough now.

You can put it in the vault by soft linking the file so that it can be automatically filled in when the file is selected.

It may be difficult to implement without a node environment on the phone if it supports files outside the library.

**Comment by artisticat1** [comment]
> Is it possible that we define the snippet in a file rather than in the setting directly, so that it can be easily maintained?

I'm not sure I understand. This feature was just implemented in 1.6.0.

If you mean you'd like to load a file located outside your vault, @windily-cloud provided a solution (thank you!).

They're right that it wouldn't work on mobile, so I don't think it'd be a good idea to implement.

**Comment by thudjx** [comment]
Oh, I found it 😂
