### ISSUE TITLE
Automatically adding space after custom snippets

### ISSUE THREAD

**Issue by nenesekai** [artisticat1/obsidian-latex-suite#71]
I wrote 2 custom snippets for land and lor, and rewrote trigger for cap and cup to avoid conflict. However there's a problem. For cap and cub it automatically add a space after i type a letter. But it does not do the same for land and lor. I don't see any differences between these 2 snippet configs and yet they don't behave the same. 
```
{trigger: "sand", replacement: "\\cap", options: "mA"},
    {trigger: "sor", replacement: "\\cup", options: "mA"},
    {trigger: "land", replacement: "\\land", options: "mA"},
    {trigger: "lor", replacement: "\\lor", options: "mA"},
```

**Comment by Asiimoviet** [comment]
After reading the snippet config I found that the adding space after command is done by this line
```
    // Insert space after greek letters and symbols, etc
    {trigger: "\\\\(${GREEK}|${SYMBOL})([A-Za-z])", replacement: "\\[[0]] [[1]]", options: "rmA"},
```
maybe for some reason the land and lor are not included in `${SYMBOL}`?

**Comment by Asiimoviet** [comment]
yeah they are not defined in here
```js
// src/snippets.ts
var SNIPPET_VARIABLES = {
  "${GREEK}": "alpha|beta|gamma|Gamma|delta|Delta|epsilon|varepsilon|zeta|eta|theta|Theta|iota|kappa|lambda|Lambda|mu|nu|xi|Xi|pi|Pi|rho|sigma|Sigma|tau|upsilon|varphi|phi|Phi|chi|psi|Psi|omega|Omega",
  "${SYMBOL}": "hbar|ell|nabla|infty|dots|to|leftrightarrow|mapsto|setminus|mid|cap|cup|subseteq|subset|implies|impliedby|iff|exists|equiv|square|neq|geq|leq|gg|ll|sim|simeq|approx|propto|cdot|oplus|otimes|times|star|perp|det|exp|ln|log|partial"
};
```
adding the command here fixed the problem. maybe add a textbox for users to customize them in options?
