### ISSUE TITLE
[FR] load snippets from multiple files

### ISSUE THREAD

**Issue by B4rc1** [artisticat1/obsidian-latex-suite#72]
Hey, I really like this plugin, to the point where I will probably be switching from my current neovim + [luasnip](https://github.com/L3MON4D3/LuaSnip) + obsidian workflow to just working in Obsidian for convenience and for live preview.

The recent addition of loading snippets from a file is awesome and made me wanna switch since I can now easily edit and sync my snippets. One thing that bothers me still is that I am constrained to just one snippet file. Could you please extend this to allow to add an arbitrary amount of files (or all files in a folder) that can be loaded as snippets?

My usecase for this would be to have a file for each subject I'm taking so I can quickly find and tweak specific snippets and phase out old snippets I no longer need because I won't need some very course specific snippets or because the current professor has a different notation.

**Comment by artisticat1** [comment]
Good idea! This can be added to a future release. Any PRs for this are also welcome.
