### ISSUE TITLE
shortcut for \frac doesn't work in ^{}

### ISSUE THREAD

**Issue by Einspieler19** [artisticat1/obsidian-latex-suite#74]
^{a/b} would not be rendered into ^{\frac{a}{b}} because the slash is used in a superscript

supposed result:
$x^{\frac{a}{b}}$
Actual result:
$x^{a/b}$

**Comment by artisticat1** [comment]
This is intended behavior. You can change this in the plugin settings (see here):

![image](https://user-images.githubusercontent.com/100622574/197880033-a71409f7-cfab-4a4f-9daf-be673f74a7eb.png)
