### ISSUE TITLE
ll expands to \ll for unknown reason

### ISSUE THREAD

**Issue by LioSergent** [artisticat1/obsidian-latex-suite#76]
Hello,
I cannot figure out why typing ll in math mode expands to \ll as I have no snippets with a ll trigger. 
How can I disable this ?

Thanks for the amazing plugin !

**Comment by artisticat1** [comment]
This is caused by [this snippet](https://github.com/artisticat1/obsidian-latex-suite/blob/904000cd27ed39a3cb6f48e6d5f41f1c05524ea0/src/default_snippets.ts#L46):

```typescript
    {trigger: "([^\\\\])(${GREEK}|${SYMBOL})", replacement: "[[0]]\\[[1]]", options: "rmA", description: "Add backslash before greek letters and symbols"},
```
