### ISSUE TITLE
Conceal mode shows "\left(" as "≤ft("

### ISSUE THREAD

**Issue by benjaminorthner** [artisticat1/obsidian-latex-suite#77]
The issue is explained in the title. Should probably be a simple fix. The "\le" within the "\left" command is misinterpreted as the less than or equal to command

**Comment by artisticat1** [comment]
Thanks for the report! This will be fixed in the next release.

**Comment by XintakXVI** [comment]
I just added a snippet `\inf` for the infimum operator ([infimum](https://en.wikipedia.org/wiki/Infimum_and_supremum)), and it is being rendered through conceal as `∈f`.

Asking for a fix doesn't feel like the right move here, since there could be an endless list of custom commands interfering with the default replacements, that users might have, and it would be a nightmare to entertain and fix each one.
Are the default replacements exposed for user editing by chance? If not, perhaps that can be considered for a later release if it's not too much trouble?
Thanks!

**Comment by artisticat1** [comment]
> I just added a snippet `\inf` for the infimum operator ([infimum](https://en.wikipedia.org/wiki/Infimum_and_supremum)), and it is being rendered through conceal as `∈f`.
> 
> 
> 
> Asking for a fix doesn't feel like the right move here, since there could be an endless list of custom commands interfering with the default replacements, that users might have, and it would be a nightmare to entertain and fix each one.
> 
> Are the default replacements exposed for user editing by chance? If not, perhaps that can be considered for a later release if it's not too much trouble?
> 
> Thanks!

I'd encourage users to report conceal errors here for them to be fixed. I'm not sure what "custom commands" users can define; given a set of LaTeX source code, there should only be a single "correct" conceal output. However, you're welcome to file a separate FR so we can see whether there is user demand for this!

I'll fix the issue with "\inf" in the next release :)

**Comment by XintakXVI** [comment]
> I'm not sure what "custom commands" users can define; given a set of LaTeX source code, there should only be a single "correct" conceal output.

Suppose a user had a custom LaTeX command `\intersect` that produces the same symbol as `\cap` (i.e., ∩). Then conceal would render `\intersect` as `∫ersect`, if I'm not mistaken.
So there's an endless list of custom commands users can come up with that start with `\int` (for example).

But thanks so much for giving `\inf` a unique conceal replacement 🙏🏽

**Comment by artisticat1** [comment]
> Suppose a user had a custom LaTeX command `\intersect` that produces the same symbol as `\cap` (i.e., ∩). Then conceal would render `\intersect` as `∫ersect`, if I'm not mistaken. So there's an endless list of custom commands users can come up with that start with `\int` (for example).

Ah, I see! That makes sense. Feel free to open a separate feature request for this.


> But thanks so much for giving `\inf` a unique conceal replacement 🙏🏽

I ran into an issue with concealing `\inf`, but will try to fix it for the next release.

**Comment by XintakXVI** [comment]
> I ran into an issue with concealing `\inf`, but will try to fix it for the next release.
No problem at all! Thanks for considering it.

> Feel free to open a separate feature request for this.
I'm a bit new to GitHub, but I'll try to check it out 🤞🏽
