### ISSUE TITLE
Auto pair $

### ISSUE THREAD

**Issue by mjkanji** [artisticat1/obsidian-latex-suite#78]
Could you please add an option to auto-pair $ (e.g., like `quick_latex_obsidian`)? 

While I prefer this plugin because of its superior snippet support, when using inline math, it's annoying to have to first close the $ and then navigate back inside the $$ in order for the snippets to actually take effect.

**Comment by QZGao** [comment]
Take this snippet :D
```
{trigger: "$", replacement: "$$0$", options: "tA"},
{trigger: "$", replacement: "$\n$0\n$", options: "mA"},
```

**Comment by mjkanji** [comment]
> Take this snippet :D
> 
> ```
> {trigger: "$", replacement: "$$0$", options: "tA"},
> {trigger: "$", replacement: "$\n$0\n$", options: "mA"},
> ```

Awesome, thanks a ton!

**Comment by rambip** [comment]
Is it possible to add this snippet, among other things, to a file in the documentation ?

It would be really helpfull
