### ISSUE TITLE
Add \text{abc} to conceal

### ISSUE THREAD

**Issue by vreithinger** [artisticat1/obsidian-latex-suite#85]
Is it possible to have \text{abc} just render to abc? maybe in another color or font to tell it apart from variables

**Comment by artisticat1** [comment]
Added in 1.6.6.

**Comment by vreithinger** [comment]
Thank you very much

**Comment by vreithinger** [comment]
Is it also possible to have it render as a sub/superskript so to have $r_\text{a}$ render as rₐ ?
