### ISSUE TITLE
Bug Report: single letter snippets at the very beginning of the note cause the plugin to crash

### ISSUE THREAD

**Issue by vreithinger** [artisticat1/obsidian-latex-suite#86]
I have the snippet

{trigger: "$", replacement: "$$0$", options: "tA"},

included to have "$" automatically autocomplete to "$[cursor]$". However, if i type a $ as the very first letter of my note, it does not autocomplete. After i have done that, no other snippet works. I have to reload the plugin to get it started again. I also tried it with other letters - same behavior. I also tried to use multiple-letter-snippets at the very beginning of the note - that works just fine. i am on obsidian 0.15.9.

**Comment by artisticat1** [comment]
Fixed in 1.6.6.

**Comment by vreithinger** [comment]
impressive how productive you are! thanks for fixing it :)
