### ISSUE TITLE
[Bug Report] `to` will auto expand to `\to` and cannot be undo with CMD+Z in Mac OS

### ISSUE THREAD

**Issue by Yaozhuwa** [artisticat1/obsidian-latex-suite#93]
Input `to` in math block will auto expand to `\to` and cannot be undo with CMD+Z in Mac OS (will input z when cmd+z), Wihle other expand operation can be undo correctly(/ expand to \frac{}{} can be undo).  I also search the config text and didn't find trigger of to.
![Screen-2022-12-07-171749(1)](https://user-images.githubusercontent.com/28787183/206138694-d8adf833-9e55-41e0-a713-8cc0484cbef9.gif)

I have test it in obsidian sand box vault.

- Obsidian 1.1
- MacOS 13.0.1 (22A400) M1 MacBook pro
- Latex-suite 1.6.7

**Comment by artisticat1** [comment]
I can't reproduce this on my machine. Are you using the default snippets?

>  I also search the config text and didn't find trigger of to.

"to" is part of the ${SYMBOL} snippet variable (see the documentation for more info!).
