### ISSUE TITLE
newcommand in latex preamble with Conceal enabled

### ISSUE THREAD

**Issue by cossio** [artisticat1/obsidian-latex-suite#94]
I have "Conceal" enabled, but this happens on the preamble :

![Screenshot 2022-12-07 at 16 32 44](https://user-images.githubusercontent.com/10637482/206221670-1e948058-dcb0-42be-8c84-d608dc479261.png)

which is suppose to be just this:

```
$$
\newcommand{\dd}{\operatorname{d}}
\newcommand{\ee}{\operatorname{e}}
\newcommand{\cov}{\operatorname{Cov}}
\newcommand{\var}{\operatorname{Var}}
$$
```

so it mistakes `\ne` with the unequal sign in the `\newcommand` directive.

Is it possible to fix this but leave "Conceal" enabled?

**Comment by artisticat1** [comment]
Sure! An option for users to customise the set of concealed symbols could be added.
