### ISSUE TITLE
Tab does not exit brackets inside matrix, align, ...

### ISSUE THREAD

**Issue by cossio** [artisticat1/obsidian-latex-suite#97]
I understand this is by design (https://github.com/artisticat1/obsidian-latex-suite#matrix-shortcuts), since inside these environments pressing `Tab` inserts a new align mark `&`. But unfortunately this means that tab can no longer be used for its usual functions (exiting a bracket, inserting a fraction snippet, etc.)

Would it be possible to change one of these keyboard shortcuts, so that we can have both a key for `&` inside matrix, align ,..., and **another** key for the usual Tab function?

It would seem better to use a different key for `&`, and leave Tab with its default function.

**Comment by artisticat1** [comment]
Thank you for the report! Closing as a duplicate of #43.
